### ISSUE TITLE
Selectively disabling supports?

### ISSUE THREAD

**Issue by kefir-** [alexrj/Slic3r#2841] opened 2015-05-22 13:31 UTC
I thought this had been discussed before, but I couldn't find a reference when searching the issue tracker.

I've been trying to print a part that requires supports. However, there are some small cavities that are not easily accessible where the support is very difficult to remove, and after printing with slic3r the cavity isn't clean enough for the mechanical fit I'm looking for. Using another slicer, I could enable support material but remove the supports in the affected areas, and the part came out fine. In slic3r, however, I can't find a way to achieve this.

I'd think it'd be possible to do this with modifiers. If slic3r had an option for this, it could for example skip building supports for overhangs inside the modifier. I think it should still build supports through the modifier if there's an overhang over the modifier, but if it could skip building supports for overhangs inside the modifier, I think we'd have a usable solution.

**Comment by Mikk36** [comment] 2015-05-22 18:47
This should be covered with this feature request: https://github.com/alexrj/Slic3r/issues/2570

**Comment by lordofhyphens** [comment] 2015-05-22 18:58
Modifier meshes allow you to do this in slic3r, it is in the 1.2.x branch.

You will need to generate a stl for the area you want. Anyone who wants to
make a better ui is welcome.

**Comment by kefir-** [comment] 2015-05-22 19:23
@Mikk36, thanks, I knew I'd seen this somewhere... 

@lordofhyphens Has this already been implemented? I use 1.2.7-dev, and my first thought was to use a modifier mesh, but I couldn't find the relevant setting for the modifier. Did I miss it?

**Comment by lordofhyphens** [comment] 2015-05-22 21:56
I could be derping hard there, unfortunately. I will take a look later.
Would be straightforward to implement though.

**Comment by mikenew12** [comment] 2015-05-22 22:00
I think you can only set support parameters at the object level, not with a modifier mesh. I would love to see this implemented as well since it would let us get around at least some of the problems with support generation.

**Comment by lordofhyphens** [comment] 2016-11-27 02:15
See my infill-over-plate branch/PR #3525 to partially cover this, those small cavities wouldn't be supported if there's no clear path straight down to the bed.

For the general case of modifier mesh + support parameters this is a dupe of #2570

**Closed by lordofhyphens** 2016-11-27 02:15 UTC
Labels: Duplicated Issue
