### ISSUE TITLE
OS X 10.9.2 - The XS/C++ code failed to compile, aborting

### ISSUE THREAD

**Issue by tsantor** [alexrj/Slic3r#1866] opened 2014-03-27 23:09 UTC
Just tried to build Slic3r on OS X 10.9.2 and got the following (This is perl 5, version 12, subversion 5 (v5.12.5)):

    sudo perl Build.PL
    App::cpanminus is up to date. (1.7001)
    Expiring 143 work directories. This might take long...
    Class::XSAccessor is up to date. (1.19)
    Encode::Locale is up to date. (1.03)
    --> Working on ExtUtils::MakeMaker
    Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-6.94.tar.gz ... OK
    Configuring ExtUtils-MakeMaker-6.94 ... OK
    Building and testing ExtUtils-MakeMaker-6.94 ... OK
    Successfully installed ExtUtils-MakeMaker-6.94 (upgraded from 6.86)
    1 distribution installed
    --> Working on ExtUtils::ParseXS
    Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-ParseXS-3.24.tar.gz ... OK
    Configuring ExtUtils-ParseXS-3.24 ... OK
    Building and testing ExtUtils-ParseXS-3.24 ... OK
    Successfully installed ExtUtils-ParseXS-3.24 (upgraded from 3.22)
    1 distribution installed
    File::Basename is up to date. (2.84)
    File::Spec is up to date. (3.40)
    Getopt::Long is up to date. (2.42)
    IO::Scalar is up to date. (2.110)
    --> Working on Math::PlanePath
    Fetching http://www.cpan.org/authors/id/K/KR/KRYDE/Math-PlanePath-114.tar.gz ... OK
    Configuring Math-PlanePath-114 ... OK
    Building and testing Math-PlanePath-114 ... OK
    Successfully installed Math-PlanePath-114 (upgraded from 113)
    1 distribution installed
    Module::Build::WithXSpp is up to date. (0.14)
    Moo is up to date. (1.004002)
    --> Working on Scalar::Util
    Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.38.tar.gz ... OK
    Configuring Scalar-List-Utils-1.38 ... OK
    Building and testing Scalar-List-Utils-1.38 ... OK
    Successfully installed Scalar-List-Utils-1.38 (upgraded from 1.35)
    1 distribution installed
    Test::Harness is up to date. (3.30)
    --> Working on Test::More
    Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.001003.tar.gz ... OK
    Configuring Test-Simple-1.001003 ... OK
    Building and testing Test-Simple-1.001003 ... OK
    Successfully installed Test-Simple-1.001003 (upgraded from 1.001002)
    1 distribution installed
    Time::HiRes is up to date. (1.9726)
    XML::SAX::ExpatXS is up to date. (1.33)
    --> Working on ./xs
    Configuring /opt/Slic3r/xs ... OK
    Building and testing Slic3r-XS-0.01 ... FAIL
    ! Installing ./xs failed. See /Users/tsantor/.cpanm/work/1395961480.74739/build.log for details. Retry with --force to force install it.
    The XS/C++ code failed to compile, aborting

**Comment by ironiridis** [comment] 2015-02-01 03:55
Checking in, same build failure. I can attach logs. Failure is in config.t. Wild guess: the issue is with dual-arch compiling and the native size of integers...?

    t/01_trianglemesh.t ............. ok
    t/03_point.t .................... ok
    t/04_expolygon.t ................ ok
    t/05_surface.t .................. ok
    t/06_polygon.t .................. ok
    t/07_extrusionpath.t ............ ok
    t/08_extrusionloop.t ............ ok
    t/09_polyline.t ................. ok
    t/10_line.t ..................... ok
    t/11_clipper.t .................. ok
    t/12_extrusionpathcollection.t .. ok
    t/13_polylinecollection.t ....... ok
    t/14_geometry.t ................. ok
    t/15_config.t ................... 1/108
    #   Failed test 'deserialize points'
    #   at t/15_config.t line 67.
    #     Structures begin differing at:
    #          $got->[0][0] = '0'
    #     $expected->[0][0] = '20'

    #   Failed test 'deserialize points'
    #   at t/15_config.t line 67.
    #     Structures begin differing at:
    #          $got->[0][0] = '0'
    #     $expected->[0][0] = '20'

    #   Failed test 'apply dynamic over dynamic'
    #   at t/15_config.t line 171.
    #     Structures begin differing at:
    #          $got->[1][0] = '20'
    #     $expected->[1][0] = '0'
    # Looks like you failed 3 tests of 108.
    t/15_config.t ................... Dubious, test returned 3 (wstat 768, 0x300)
    Failed 3/108 subtests
    t/16_flow.t ..................... ok
    t/17_boundingbox.t .............. ok
    t/18_motionplanner.t ............ ok
    t/19_model.t .................... ok
    t/20_print.t .................... ok

    Test Summary Report
    -------------------
    t/15_config.t                 (Wstat: 768 Tests: 108 Failed: 3)
      Failed tests:  24, 73, 103
      Non-zero exit status: 3
    Files=19, Tests=445,  1 wallclock secs ( 0.13 usr  0.07 sys +  1.01 cusr  0.19 csys =  1.40 CPU)
    Result: FAIL
    Failed 1/19 test programs. 3/445 subtests failed.
    FAIL
    ! Installing ./xs failed. See /Users/charrington/.cpanm/work/1422762538.1465/build.log for details. Retry with --force to force install it.
    The XS/C++ code failed to compile, aborting

**Comment by ironiridis** [comment] 2015-02-01 04:22
I commented earlier that I was experiencing this issue. I'd been trying to build Slic3r on OS X for some time and had continued running into this same issue. Turns out that `git reset --hard` was somehow not clearing out temporary build products. After re-cloning the repo, build is successful.

OS X 10.10.2 (14C109)

    $ gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
    Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin14.1.0
    Thread model: posix

----

    $ perl -V
    Summary of my perl5 (revision 5 version 18 subversion 2) configuration:

      Platform:
        osname=darwin, osvers=14.0, archname=darwin-thread-multi-2level
        uname='darwin glow.apple.com 14.0 darwin kernel version 14.0.0: tue aug 19 19:20:45 pdt 2014; root:xnu-2782.1.85~1development_x86_64 x86_64 '

You can probably close this issue unless someone can reproduce?

**Comment by lordofhyphens** [comment] 2016-07-12 23:28
Closing, please comment if you can reproduce the issue.

**Closed by lordofhyphens** 2016-07-12 23:28 UTC
