### ISSUE TITLE
Missing solid horizontal top layers under slopes

### ISSUE THREAD

**Issue by davidpelletierburns** [alexrj/Slic3r#3305] opened 2016-04-14 17:43 UTC
Version 1.2.8
OSX 10.11.4

Behaviour
I am having an issue with any shape I slice that has to generate solid horizontal layers under slopes.

Slic3r correctly puts the wanted amount of layer under any horizontal plane; but only considers perimeters if next(z) layers are at an angle.

<img width="760" alt="screen shot layers" src="https://cloud.githubusercontent.com/assets/18468220/14536624/6047e600-0241-11e6-8829-75206bb8a067.png">
You can see in this picture that layer in the center (under flat plane) are correctly solid. But around it they are not.

Files
[Archive.zip](https://github.com/alexrj/Slic3r/files/219656/Archive.zip)

BTW thanks for the great app!

**Comment by lordofhyphens** [comment] 2016-06-20 03:05
Looks like a duplicate of #2338. Please reopen if you can show otherwise.

**Closed by lordofhyphens** 2016-06-20 03:05 UTC
Labels: Duplicated Issue
