### ISSUE TITLE
Perimeter inside bridge printed in free space

### ISSUE THREAD

**Issue by mistoll** [alexrj/Slic3r#3422] opened 2016-07-13 14:19 UTC
### Version 
1.2.9

### Operating system
Windows 7

### Behavior

When there's a hole in a bridge, the perimeter of the hole is printed without anything to print on being present. 

![bridgeing problem_2](https://cloud.githubusercontent.com/assets/941621/16806386/97e041a6-4914-11e6-9eb0-963c54d9ef35.PNG)
Left is ok, right does not work.

Simple object for reproduction
![bridgeing problem_1](https://cloud.githubusercontent.com/assets/941621/16806392/9db0dff0-4914-11e6-8dad-d277a35df6cc.PNG)

This is related to #657. 

#### STL/Config (.ZIP) where problem occurs
[config_stl.zip](https://github.com/alexrj/Slic3r/files/361637/config_stl.zip)

**Comment by lordofhyphens** [comment] 2016-07-13 14:36
Yep, that's an overhang and is basically impossible to print without
support.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by mistoll** [comment] 2016-07-13 16:43
I agree that there are cases where there is no solution for this problem. The circle may be one of them.

Let's look a the rectangular hole. My idea would be to print a bridge aligned to one edge, omitting any bridge with a hole. After that print another bridge twisted by 90°, aligned to the other edge and attached to the bridge printed before. However I'm not sure if attaching one bridge to another would work.

You can see our workaround in the model. There we split the bridge into to layers.

**Comment by FlameRunner** [comment] 2016-07-14 12:23
If you insist on not using supports, try modelling with one-layer-height diaphragm. That kinda works even with circles.

**Comment by mistoll** [comment] 2016-07-14 16:29
That sound like a good workaround. I'll give it a try.

**Comment by lordofhyphens** [comment] 2016-07-14 16:53
Duplicate of #2621, with note by @FlameRunner as #254 (for Slic3r to do it for you).

Closing.

**Closed by lordofhyphens** 2016-07-14 16:53 UTC
Labels: Duplicated Issue
