### ISSUE TITLE
slic3r 1.2.9 ignoring print centre values when slicing through the commandline

### ISSUE THREAD

**Issue by jgrjgr** [alexrj/Slic3r#3280] opened 2016-03-20 00:30 UTC
Hi all,

there is an issue with 1.2.9 where under the commandline it produces gcode based on an assumption that the print centre is X100 Y100 which is fine for most reprap beds, however if your bed is a bit larger eg  400x200 it still outputs gcode centred around X100 Y100 when it should be centred around the print centre values which are 200x100

I've managed to reproduce this across windows: 7 , 8.1 and 10 machines on 32bit and 64bit systems
all relavant files are here: https://www.dropbox.com/sh/8flsems65epn82z/AABKjGkJF3WgkLkkr4c3W1MJa?dl=0

the commandline usage was:

slic3r-console.exe cube.stl -load config-big.ini

**Comment by alexrj** [comment] 2016-03-20 01:00
Thank you, duplicate of #2725

**Closed by alexrj** 2016-03-20 01:00 UTC

**Comment by jgrjgr** [comment] 2016-03-20 02:43
that issue is about the value being generated dynamically based on bed size, i'm talking about it ignoring the values placed in the config.ini
