### ISSUE TITLE
Cannot disable skirt

### ISSUE THREAD

**Issue by swpaxton66** [alexrj/Slic3r#2694] opened 2015-02-25 18:34 UTC
I have what I believe is to be a bug. I cannot disable the skirt. I have all options disabled and the skirt is always generated. Please advise on what supporting info is required to root cause the issue. I am using 1.7.1 (last stable release)

**Comment by harriv** [comment] 2015-02-25 19:50
Please read the guidelines: https://github.com/alexrj/Slic3r/blob/master/CONTRIBUTING.md

Unless you post at least your config (and maybe the .stl file), it's impossible to help.

**Comment by alexrj** [comment] 2015-02-27 17:45
Also test 1.2.6.

**Comment by lordofhyphens** [comment] 2016-07-13 00:46
Can't reproduce on 1.3.0, and I don't think I've run into this myself. Nor were steps to reproduce problems posted. 

Closing.

**Closed by lordofhyphens** 2016-07-13 00:46 UTC
Labels: Needs more info
