### ISSUE TITLE
Slic3r 1.2.6 stops when loadingbar is allmost @ 100% 

### ISSUE THREAD

**Issue by spirit18** [alexrj/Slic3r#2660] opened 2015-02-15 09:39 UTC
first of all i like your software
but the latest beta version stops working if the loadingbar is allmost at 100%
look movie i added.
https://www.dropbox.com/s/s9e4682clr40sco/Desktop%2002.15.2015%20-%2010.35.46.01.mp4?dl=0

i tried it with 32bit and 64 bit. same results.
and it only happins when i add a Object.

**Comment by alexrj** [comment] 2015-02-15 12:22
Can you please provide the things described in the guidelines please? Otherwise it's impossible to reproduce the problem.

**Comment by spirit18** [comment] 2015-02-15 13:23
Oww sorry my bad never seen the guidelines.
Config file : https://www.dropbox.com/s/63wwwylgepdx9vk/%232660.ini?dl=0
Object: https://www.dropbox.com/s/8jefcrjqlxy1dqo/feeder%20hulp%20v1%20flipt%20180.stl?dl=0

PC specs:
Windows 7 Home premium (64bit)
AMD FX-6100 (@ 6x 3.6Ghz)
8 GbRam
2x 256 SSD raid0
Nvidia GTX 770, 4GbRam
ROG crosshair V formula-Z, motherboard.

Steps to reproduce:
1) open Slic3r 1.2.6 (32 or 64 bit)
2) add object
3) wait until loading bar is @ 100%
4) Slic3r stops working.
There are NO error massages

**Comment by justmyopinion** [comment] 2015-02-15 14:14
Maybe only lack of patience here.
I have about the same setup and do slice your file, but it may take some more time than expected.
Reason is a known lack of performance with Slic3r when "printsettings/avoid_crossing_perimeters" has been enabled, causing slicetime to be excessive.
Uncheck this and see that your slice will be fine.

**Comment by spirit18** [comment] 2015-02-15 14:37
i dont mind waiting sometimes it take up to 30 min.
but the problem as you can see on the Movie (seems you did not look at it, more a lack of patience to read the whole issue report here.)
Slic3r just Closes when the Loading bar is near 100%

**Comment by justmyopinion** [comment] 2015-02-15 15:27
ok, but that is not what happens with ver 1.2.6, my Win7/64 and your config/STL file. It slices fine in both cases also when exporting gcode.

**Comment by spirit18** [comment] 2015-02-15 15:49
Oke nice.
i found out the issue i have. 

Poeple (like me) need to update Windows 7. (realy odd as i got new udates yesterday) 
and i think its because i did not have the latest "microsoft .NET Framework 4.5.2" now it work fine :-D

some one can close this issue.

**Comment by justmyopinion** [comment] 2015-02-15 16:02
Well the issue was not described as "crashing, but just "stopped working" :-) so for security reason I mostly avoid entering movies.
Never mind, good you found a solution.

**Comment by spirit18** [comment] 2015-02-15 16:47
it depant on how you look at "crashing" and "stopped wroking"
but i see your point.
"crashing" to me, means i get a massege from windows asking me if i like to "End Task " (Not responding) so the software realy crashes.
"stops working" means No message, just pops back to desktop.

**Comment by spirit18** [comment] 2015-02-15 16:57
oke wait its back again.. strange!

**Comment by lordofhyphens** [comment] 2015-02-15 17:14
We need to know what settings you were using (export config) and a copy of
a model you were seeing this issue with. Otherwise we can't reproduce the
issue. If we can't reproduce, can't fix.

**Comment by SpencerCWatson** [comment] 2015-02-17 06:47
Hopefully I can add to fixing this because I am having the same issue. I happens in both windows 7(My other computer) and 8.1.

 It happens just as the video shows, add part and right before the loading bar is full Slic3r will close. For me it mostly happens with round objects and it does not matter if it is my settings or default settings.

PC specs:
Windows 8.1 (64bit)
Intel i7 4 core 2.8GHz
8 GbRam
256 SSD
Nvidia GTX 870M

https://drive.google.com/folderview?id=0BwItvBIsxpO9blo4OWlzRnNFT28&usp=sharing

**Comment by SpencerCWatson** [comment] 2015-02-17 07:42
OK I have been playing with this for an hour now and it looks like deleting the C:\Users\(your own personal user name)\AppData\Roaming\Slic3r and then importing my settings back in fixed it. Not sure why I had issues in the first place but it seems to be working now.

**Comment by alexrj** [comment] 2015-06-02 19:48
@spirit18 and @SpencerCWatson, this looks fixed as of 1.2.7.  Please feel free to reopen if not. Thank you for reporting the issue.

**Closed by alexrj** 2015-06-02 19:49 UTC
Labels: Needs more info, Needs test STL file
