### ISSUE TITLE
Bridge slicing path messed up

### ISSUE THREAD

**Issue by sudoeste** [alexrj/Slic3r#3570] opened 2016-11-10 01:51 UTC
### Version
Latest from repetier-host, it says latest when trying to update inside slic3r settings

### Operating system type + version
Windows 10

### Behavior
Slice the following model
http://www.thingiverse.com/thing:1729459
* _Expected Results_
the first bridge layer should be uniform (Cura does it)
* _Actual Results_
![slicer](https://cloud.githubusercontent.com/assets/3848104/20161675/f2a68fce-a6e7-11e6-8a2c-cab1d73806d4.PNG)
_Is this a new feature request?_
no

**Comment by lordofhyphens** [comment] 2016-11-10 02:57
Need a screenshot from inside Slic3r itself.

**Comment by sudoeste** [comment] 2016-11-10 03:07
Sure thing. All default settings
![capturar](https://cloud.githubusercontent.com/assets/3848104/20163227/b679b034-a6f2-11e6-8ede-a8fad5abf67e.PNG)

**Comment by lordofhyphens** [comment] 2016-11-10 03:44
Have you tried with a 1.3.0-dev version? 
https://bintray.com/lordofhyphens/Slic3r/slic3r_dev/1.3.0-master-183#files
![image](https://cloud.githubusercontent.com/assets/31754/20163879/b55dfef8-a6c5-11e6-86f0-de9cbdc8d06f.png)

**Comment by lordofhyphens** [comment] 2016-11-10 03:47
Just FYI, the 2d layer view won't  show you previous layers, but 3D will (3D will also show you what Slic3r expects the widths to be). 
Configuration: [config.zip](https://github.com/alexrj/Slic3r/files/582482/config.zip)

**Comment by sudoeste** [comment] 2016-11-10 03:52
I'm new to this world :) 

Nop, I haven't tried the dev build, just the download from the main site. So I guess it's fixed but only in the 1.3 branch?

**Comment by lordofhyphens** [comment] 2016-11-10 03:56
Apparently so.

This is roughly equivalent to building the source yourself (there are
instructions for doing so).

It should be possible to use the dev version of slic3r with RepHost (point
it at the batch file instead of an exe). I haven't tried though. I don't
have any use for RepHost myself.

**Comment by sudoeste** [comment] 2016-11-10 04:01
I'm new to the 3d world not how building from source works (although I can't program anything even if my life depends on it) . 

So this probably won't be fixed upstream?

**Comment by lordofhyphens** [comment] 2016-11-10 04:28
You are upstream :)

It should be fixed in the next release, whenever that is. If you want to
get the benefit before that, there is the bintray.com builds (which I
linked earlier).

Take a look at the wiki tab here on github, there are instructions for
running from git on windows, which is what you would need to do if you want
to build it yourself. If the bintray.com builds serve your needs, then
great :)

**Comment by micscopau** [comment] 2016-11-12 18:46
I'm having a similar issue that I would describe as a bad bridge slicing path 

**Version:** slic3r 1.3.0-dev 

trying to print:
http://www.thingiverse.com/thing:1179160

Internally there is a solid perimeter that bridging could use for anchoring (first picture), but instead has bridge paths stopping above free space (second picture). 

Thanks!

![layer 18 0](https://cloud.githubusercontent.com/assets/7364791/20240074/94491a78-a8cc-11e6-935c-a7a3d3a2a2bc.PNG)

![layer 18 20](https://cloud.githubusercontent.com/assets/7364791/20240075/9640f4e0-a8cc-11e6-9a63-cb26c7cbff9f.PNG)

**Comment by bubnikv** [comment] 2016-11-12 18:53
This issue has been fixed to a large extent in the recent prusa3d fork. If
the bridging regions are very close, then they are merged together.


[image: Inline image 1]

**Comment by bubnikv** [comment] 2016-11-21 11:49
Duplicate of https://github.com/alexrj/Slic3r/issues/3578

**Comment by lordofhyphens** [comment] 2017-01-25 16:48
Going to close as #3578 has a longer comment trail and I can't reproduce with the original file on 1.3.0-dev.

**Closed by lordofhyphens** 2017-01-25 16:48 UTC
Labels: Can't Reproduce - Development Build, Duplicated Issue
