### ISSUE TITLE
[1.2.7-dev] [Windows] Errors reading preset files

### ISSUE THREAD

**Issue by nicoruy** [alexrj/Slic3r#2787] opened 2015-04-16 13:31 UTC
After saving a preset slic3r shows a set of error messages and crashes.
This happens both on basic and expert mode.
On Basic mode the messages are presented when the application starts.
On Expert mode it happens when the save button is pressed on the settings tabs.
You can see the errors on the attached screenshots.
The first message is presented twice.

The problem might be related to the issue #2645 (I have special characters on my path)
![captura de pantalla 2015-04-15 22 29 41](https://cloud.githubusercontent.com/assets/11979039/7181745/48ec9880-e423-11e4-9fb0-eaf80c981383.png)
![captura de pantalla 2015-04-15 22 29 48](https://cloud.githubusercontent.com/assets/11979039/7181746/48eda0a4-e423-11e4-8599-f28e91c4bdb9.png)
![captura de pantalla 2015-04-15 22 29 52](https://cloud.githubusercontent.com/assets/11979039/7181747/48f02f72-e423-11e4-9540-7267db4a52b4.png)

**Comment by alexrj** [comment] 2015-05-06 08:49
@nicoruy, should should be fixed and I can't reproduce it (I tested on a Windows 7 machine having username with a "à" letter in it)... Since you didn't specify the commit you were running at the time of the report, could you please `git pull` now and `perl Build.PL` (making sure the build succeeds) and let me know if this still happens? Thank you!

**Comment by clefranc** [comment] 2015-05-21 14:41
@alexrj  I reproduced this problem using the celcius character in the preset: **Test Temp 230°C**.
Exact same dialog messages, except in French. Hope this help!

**Comment by alexrj** [comment] 2015-05-24 14:00
@clefranc, what Slic3r version?

**Comment by clefranc** [comment] 2015-05-24 15:57
@alexrj 1.2.6

**Comment by alexrj** [comment] 2015-05-24 19:51
@nicoruy and @clefranc: can you check whether 1.2.7 (released today) fixes this? Thank you!

**Comment by clefranc** [comment] 2015-05-25 01:07
@alexrj Same error with 1.2.7.

When using Repetier-Host, I can use the **Test Temp 230°C** to generates g-code without error.

**Comment by alexrj** [comment] 2015-06-09 19:20
@nicoruy, @clefranc, could you please try with 1.2.8? This should be fixed now. Thank you

**Comment by alexrj** [comment] 2015-06-20 13:40
@nicoruy, @clefranc, could you please try with 1.2.9 and confirm this was fixed? Thank you!

**Comment by clefranc** [comment] 2015-06-21 21:50
@alexrj Sorry for the delay, back from vacation...

Yes, I confirm it's fixed with 1.2.9. Thank you!

**Comment by alexrj** [comment] 2015-06-21 21:50
Thank you @clefranc!

**Closed by alexrj** 2015-06-21 21:50 UTC
Labels: Needs testing with current dev version or next release, OS: Windows
