### ISSUE TITLE
Peculiar & Inconsistent Bridging

### ISSUE THREAD

**Issue by ednisley** [alexrj/Slic3r#2646] opened 2015-02-09 13:51 UTC
Recent versions (through 0d822f0) produce unusual (and unusable) bridges on my Chain Mail models. This seems related to other bridging problems, but in these cases, identical shapes produce different results; perhaps that can help track down what's going wrong.

As nearly as I can tell, the bottom layer of all bridges _generally_ uses the infill pattern for the current layer, rather than the direct-across bridge pattern. This doesn't come from a difference in the models, because all of the chain mail links come from the same OpenSCAD object and are identical.

For example, three of these four bridges use infill across the link bars:

![slic3r bridging - links](https://cloud.githubusercontent.com/assets/599600/6106668/593ca6b0-b031-11e4-8883-ea86a43b5938.png)

The single correct bridging pattern spans the far right-rear bar in a larger group of links:

![slic3r bridging - caps 1](https://cloud.githubusercontent.com/assets/599600/6106821/f9dd6a5e-b032-11e4-9df9-1b542df81216.png)

The first layer of bridging for the "armor" caps on the 2x2 array of links in the middle shows both infill and bridging patterns:

![slic3r bridging - caps 2](https://cloud.githubusercontent.com/assets/599600/6106860/32c50e08-b033-11e4-9706-626d1b980b17.png)

The bridging in the right rear cap combines _both_ patterns, with a few bridge threads spanning the left edge and diagonal infill across the remainder.

[Edit: The left rear cap has correct bridging across the entire top of the link, with good anchors on both sides. Sometimes bridging works perfectly!]

The same type of problem appears with the default Slic3r configuration, as well as my customized MakerGear M2 configuration. Of course, the exact results vary unpredictably with the exact values for all the perimeter / infill parameters. I have yet to find a combination that produces the same results as the older versions that let me produce large chain mail sheets with uniformly good bridges:

![cimg7446 - chain mail armor buttons - full sheet folded](https://cloud.githubusercontent.com/assets/599600/6106997/6e3a02d0-b034-11e4-9569-bb79764a10b7.jpg)

That sheet was printed in late November 2014. The comment at the top of the G-Code file reads:

    ; generated by Slic3r 1.2.1 on 2014-11-27 at 16:41:09

Slic3r doesn't report any problems with these STL files; they're all manifold. The models include slight (on the order of 0.05 mm) protrusions or recesses at the openings to eliminate coincident edges and surfaces, but changing / eliminating those doesn't affect the  bridging problems.

The parameters at the top of the OpenSCAD program provide fine-grained control over the exact model dimensions and chain mail link attributes.

This is done with Xubuntu 14.04LTS and compiled-from-source versions of OpenSCAD through 37421bb.

The OpenSCAD, STL, and Slic3r config.ini are in:
https://www.dropbox.com/s/nm20qqbjipum10e/Slicer%200d822f0%20-%20bridging.zip?dl=0

If I can run any other tests to help track down the problem, let me know!

Thanks ...

**Comment by Ghoughpteighbteau** [comment] 2015-02-19 03:54
I'm having difficulties with this as well. Slicer makes odd choices when it's bridging over unsupported area's. It should span gaps as much as possible.

In this case in particular I'd love it if slicer just used a rectilinear pattern, because it would work!

![example of bad bridging patterns](http://i.imgur.com/TgHl1bk.png)

STL's to test on: 

https://www.dropbox.com/s/darjs2byyex5zis/testbricklego2.stl?dl=0
https://www.dropbox.com/s/u06sb01oz1r89k3/testbricklego.stl?dl=0

**Comment by MadMarkTheSane** [comment] 2015-02-21 17:23
# Simpler Test Case and Possible Work Around
Firstly I think I have identified which version introduced this problem.  Here is a simpler test model which also exhibits the same fault sliced with version 1.2.1:
![bridgedirections_v1 2 1](https://cloud.githubusercontent.com/assets/11135998/6314967/3a2987b2-b9ea-11e4-836b-bf1fad8ef66d.png)
And the same model sliced with version 1.2.2:
![bridgedirections_v1 2 2](https://cloud.githubusercontent.com/assets/11135998/6314964/32c0bad6-b9ea-11e4-816b-ddbbb23cea1d.png)
As Ed orignialy reported it seems that only one bridge is being detected per layer.
I can confirm this bug exists in versions 1.2.2 to 1.2.6, windows x64 and linux x64 builds from the web site.  All tests were done with a 'default' configuration by clearing out slic3r's config directory between each test.
## Possible workaround
If the model contains multiple solids and you can 'split' the the model using the toolbar then versions 1.2.2 to 1.2.6 correctly generate the bridge directions again.
![bridgedirections_split_v1 2 2](https://cloud.githubusercontent.com/assets/11135998/6315025/bc23b782-b9eb-11e4-9e0e-0d06db8c544a.png)
Of course this wont help if the model is a single solid.  I'm not sure if it will help in your case Ed, as I think once split your chain mail parts will be re-arranged and become unlinked.
I would seem that slic3r is no longer detecting multiple bridges on the same layer and optimising directions for them which gave me a thought:
![framevetex_v1 2 2](https://cloud.githubusercontent.com/assets/11135998/6315045/caa6c51e-b9ec-11e4-901c-b96b2ba919f9.png)
**It breaks the frame vertex test case as shown on the website!**
## Link to my test files and config
http://1drv.ms/1Av7qxc

**Comment by ednisley** [comment] 2015-02-21 17:56
> once split your chain mail parts will be re-arranged

All the links remain in place after splitting the mesh! Clicking Arrange does exactly what you'd expect, but until then nothing moves.

Unfortunately, every link has two bars that require bridges on the same level and, even though they're parallel, one bar still gets the infill thread orientation.

The larger armor caps, however, all bridge perfectly, so the problem happens only with multiple bridges on the same layer within a single object.

Most of my designs look like brackets: a single object with multiple bridges. If I can gimmick each bridge onto a separate layer, then your workaround will dodge the problem until an official fix arrives.

Thanks!

**Comment by MadMarkTheSane** [comment] 2015-02-21 20:24
Happy to have helped a bit at least!

Seems like we should have enough information on this issue here for someone who knows what they are doing to take a look at it.  If I knew the first thing about Perl I might be tempted to take a look at it myself but unfortunately when it gets above the C/C++ level I'm way out of my comfort zone!

**Comment by Ghoughpteighbteau** [comment] 2015-02-23 02:35
At least in my case, the ability to disable the bridging algorithm would be a nice stopgap.

**Comment by alexrj** [comment] 2015-02-27 20:58
This regression was fixed in #2636. Thank you for reporting it.

**Closed by alexrj** 2015-02-27 20:58 UTC
