### ISSUE TITLE
Supports are not detecting correct overhang values

### ISSUE THREAD

**Issue by Tinchus2009** [alexrj/Slic3r#3860] opened 2017-04-06 02:21 UTC
### Version
1.2.9-944-g04b59af

### Operating system type + version
win10 64b

### Behavior
In the support configuration, if you set a value in degrees, no matter what you use, supports will be generated all over the place, even in vertical walls
If you use % values: if you use default (120%) you get what you can see in the screenshot, supports are generated in an almost vertical wall. Most strange, if you increase the value in an attemp to make these supports to desapear, in my example I used 150%, the supports that were ok and actually necesary, desapeared, and the ones in the almost vertical wall remains (and actually totally unnecesary)
[falla3.zip](https://github.com/alexrj/Slic3r/files/901302/falla3.zip)

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_

**Comment by lordofhyphens** [comment] 2017-04-06 13:17
Very likely a duplicate of #3842 and you are missing a test STL.

**Closed by lordofhyphens** 2017-04-06 13:17 UTC
Labels: Duplicated Issue
