### ISSUE TITLE
Honeycomb infill is offset - 1.2.6

### ISSUE THREAD

**Issue by BJoey** [alexrj/Slic3r#2693] opened 2015-02-25 14:12 UTC
didn't find any similar issue so i'll open one:
since using Slic3r 1.2.6, the honeycomb infill layers do not always align correctly, as seen in the picture. Does not connect with perimeters as well and seems to get worse with smaller layer heights. this causes a great loss of stability and top layers are not properly filled due to the lack of material in the layers below.
Did I change any option to make this happen or is it a real bug?
![img_20150225_145450](https://cloud.githubusercontent.com/assets/11194145/6371886/4f59a2e8-bd00-11e4-9bb4-164f7c2a0bde.jpg)

**Comment by a4jp-com** [comment] 2015-02-25 23:19
I have the same problem.

**Comment by alexrj** [comment] 2015-02-27 21:33
@BJoey, see the guidelines. We need to reproduce your problem in order to help or take any action.

**Comment by a4jp-com** [comment] 2015-02-28 01:43
If BJoey can't post a file I can try and make a 3D model again with this problem. I deleted all the files I had before because they just looked ugly. I just had a land model with a honeycomb infill set at about 20 or 30 percent. Kind of a box with the bottom turned off.

**Comment by BJoey** [comment] 2015-02-28 10:12
Hey sry I can't figure out how to upload a file, but that proplem does not depend on a specific STL file. The picture above is a print of this one: http://www.thingiverse.com/thing:65168
I can post the GCode of one of those prints or Slic3r settings if it helps:


# generated by Slic3r 1.2.6 on Sat Feb 28 11:09:23 2015
avoid_crossing_perimeters = 0
bottom_solid_layers = 4
bridge_acceleration = 0
bridge_flow_ratio = 1
bridge_speed = 30
brim_width = 0
complete_objects = 0
default_acceleration = 0
dont_support_bridges = 0
external_fill_pattern = rectilinear
external_perimeter_extrusion_width = 0
external_perimeter_speed = 50%
external_perimeters_first = 1
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 20
extrusion_width = 0
fill_angle = 45
fill_density = 50%
fill_pattern = honeycomb
first_layer_acceleration = 0
first_layer_extrusion_width = 200%
first_layer_height = 0.3
first_layer_speed = 50%
gap_fill_speed = 20
gcode_comments = 0
infill_acceleration = 0
infill_every_layers = 2
infill_extruder = 1
infill_extrusion_width = 0
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 15%
infill_speed = 60
interface_shells = 0
layer_height = 0.1
min_skirt_length = 0
notes = 
only_retract_when_crossing_perimeters = 1
ooze_prevention = 0
output_filename_format = [input_filename_base].gcode
overhangs = 1
perimeter_acceleration = 0
perimeter_extruder = 1
perimeter_extrusion_width = 0
perimeter_speed = 40
perimeters = 3
post_process = 
raft_layers = 0
resolution = 0
seam_position = nearest
skirt_distance = 3
skirt_height = 1
skirts = 1
small_perimeter_speed = 30
solid_infill_below_area = 70
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0
solid_infill_speed = 60
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_contact_distance = 0.2
support_material_enforce_layers = 0
support_material_extruder = 1
support_material_extrusion_width = 0
support_material_interface_extruder = 1
support_material_interface_layers = 0
support_material_interface_spacing = 0
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 2.5
support_material_speed = 60
support_material_threshold = 0
thin_walls = 1
threads = 2
top_infill_extrusion_width = 0
top_solid_infill_speed = 40
top_solid_layers = 4
travel_speed = 130
xy_size_compensation = 0

**Comment by lordofhyphens** [comment] 2016-07-12 23:51
Looks like it's related to the width detection or infill_every_layers. For some reason, the first layer of internal infill is getting a wider infill than the ones above it and it's probably messing with the spacing.

first layer of infill:
![first_infill](https://cloud.githubusercontent.com/assets/31754/16787262/9a1dec34-4860-11e6-97a2-29348c660860.png)
second layer of infill
![second_infill](https://cloud.githubusercontent.com/assets/31754/16787261/9a1b7d00-4860-11e6-8fde-71fd03d73ac1.png)

Only the lowest layer is getting the declared width of 1.98mm (in the gcode).

Setting the width manually sorts things out, as did setting infill_every_layers = 1 or PR #3410. 
@BJoey you could use my branch or do what I mentioned above. I would suggest using my branch because  combined infill isn't going to work like you expect it to anyway with the current code (it will make the part weaker).

Branch with fix:
https://github.com/lordofhyphens/slic3r/tree/fix-combine-infill

**Comment by alexrj** [comment] 2016-12-21 19:01
@lordofhyphens, since your PR was merged I assume this issue is fixed. Is this right?

**Comment by lordofhyphens** [comment] 2016-12-21 20:57
I'll check all of these PRs tonight when I get home from work and close
them if my test cases pass.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment] 2016-12-22 06:50
It looks like they're aligning properly now according to the provided test case, although the preview is drawing the upper layers thinner (this may just be because of combine-infill not having a good layer-by-layer draw method). I'd appreciate it if @BJoey would check it as well on his end :)

**Comment by alexrj** [comment] 2016-12-22 09:36
@lordofhyphens, rendering of combined infill should be proper. If last layer is thinner maybe it's because an even number of layers are configured for combination and there is an odd number of them, so the last one is not combined... is this the case?

**Comment by lordofhyphens** [comment] 2016-12-24 17:06
0.90 (first layer is 0.3, successive are 0.2)
![image](https://cloud.githubusercontent.com/assets/31754/21467960/16f1a08a-c9c5-11e6-9fa3-7f8695477495.png) 
It's the bottom sparse infill layer that's fat.

0.70 ![image](https://cloud.githubusercontent.com/assets/31754/21467979/526e6832-c9c5-11e6-9b30-27a39041ee0d.png)

4.90 - last layer before the sloping begins 
![image](https://cloud.githubusercontent.com/assets/31754/21467985/732466d0-c9c5-11e6-8fcc-d40c5a87cee5.png) 

Last layer of combined sparse infill is at 19.70, so I'm not seeing an odd/even thing going on here.

**Comment by lordofhyphens** [comment] 2017-03-11 14:35
![image](https://cloud.githubusercontent.com/assets/31754/23824053/357009be-0635-11e7-9b72-e8ce574ff234.png)
Current behavior looks like it's tied to auto-width. The upper layers are drawn at a higher effective layer height than the lowest layer (and it's known that the auto-calculation has surprising results at low layer heights.

**Comment by lordofhyphens** [comment] 2017-03-11 14:36
![image](https://cloud.githubusercontent.com/assets/31754/23824083/d1b7d66c-0635-11e7-8a75-b8b678fd90a1.png)

**Comment by lordofhyphens** [comment] 2017-03-11 14:37
0.5 fixed width for infill:
![image](https://cloud.githubusercontent.com/assets/31754/23824093/fec698c8-0635-11e7-923e-71d2ba766a9b.png)

**Comment by lordofhyphens** [comment] 2017-03-11 14:45
I think it's behaving as it's been designed to, though, so I think we can close this and I'll reference this in either another issue for automatic line widths (or to another one if it exists)

**Closed by lordofhyphens** 2017-03-11 14:45 UTC
Labels: Fixed with PR available to merge
