### ISSUE TITLE
Enable support features with modifier meshes

### ISSUE THREAD

**Issue by phizz166** [alexrj/Slic3r#2937] opened 2015-06-21 23:54 UTC
So I was trying to print this part the other day

http://www.thingiverse.com/thing:34343

(I scaled it to 25% and was using 0.15 layers)

With proper settings and good filament cooling, there is only a single part of the model that needs support: directly underneath his left hand. Everything else prints fine thanks to steep angles or bridging. However, for some reason I couldn't find a threshold angle for the support that would get only his hand. Setting it to e.g. 1 degree did nothing, even though the hand is fully overhung (even a bit negative). In fact, no angles below 16 degrees generated any support on the model, while 17 degrees created support in many different places (under the chest and head, etc). I don't want this.

That may be an issue in itself (particularly the overhang detection not working until 17 degrees even on the hand area), but it's not what I'm interested in. I realized that to solve this, I could just create a modifier mesh that covered a volume from the model's base plane up to the hand, and turn on "generate support" for that area with a really generous threshold angle. Problem solved...?

...but you can't alter support settings with modifier meshes, it seems. Can this functionality be added? It would be a good step on the way to something like Simplify3D's manual support definition, which is just awesome.

**Comment by lordofhyphens** [comment] 2016-04-18 13:26
Duplicate of #2570

**Comment by lordofhyphens** [comment] 2016-12-06 19:13
Closing as it is a dupe.

**Closed by lordofhyphens** 2016-12-06 19:13 UTC
Labels: Duplicated Issue, Feature request
