### ISSUE TITLE
2018 Feature Request - Outlines height / infill height separate , Beautifull object for the same time of low quality printing

### ISSUE THREAD

**Issue by studiodyne** [alexrj/Slic3r#4258] opened 2018-01-12 12:29 UTC
Hi , this is just for inspiration, just an idea but if Slic3r Devs make it , it's a big new release for 2018 that will up the slic3r to the first position of this category of software
I have found a name for this 
**DUAL-SLICING** 

Imagine , Slic3r have separate settings for outlines and infill , and the intelligence to combine these
For example  0.1mm for outlines and 0.4 for infills
The object will have an amazing looking and the time to make it is approximatively the same of a low quality printing. All overhangs and many angles are processed in high resolution too

The process need to be intelligent
Two slicing process
One with the big layer height  and the ' REMAINING MATTER not printed ' will be sliced with the thick height
The slicer combine all , and the print can begin

Advantage of a high resolution for all outlines , curved roof or overhangs and more , and the high resolution is just used where is needed , and the rest is printed with high height

Maths 👍 
4x or more outlines time
4x or  less infills time   
Infills time > outlines time  , if infills/4 we ensure the global print time will be shorter even thought a four time outlines printing

Thks

**Comment by platsch** [comment] 2018-01-12 13:53
as already pointed out in the Marlin firmware tracker https://github.com/MarlinFirmware/Marlin/issues/7597#issuecomment-356276369 this is implemented and used by many people for years.

Just set `Combine infill every` to a number > 1.
The idea is not new, the first description I'm aware of can be found in Emmanuel Sabourin master thesis "Adaptive High-Precision Exterior, High-Speed Interior, Layered Manufacturing" http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.556.1100

**Comment by supermerill** [comment] 2018-01-15 15:09
duplicate of #1201 ?

**Comment by platsch** [comment] 2018-01-15 19:28
@studiodyne can we close this or do you still see a missing point?

**Comment by studiodyne** [comment] 2018-01-15 20:39
It's ok , and i'm happy , to see , the idea , is already in many brains , i will look at the other posts here

You can close , and many thanks for devs jobs 
Very good job !

**Closed** 2018-01-15 20:40 UTC
