### ISSUE TITLE
Slicing Crashes (OOM killer) When Using any Supports

### ISSUE THREAD

**Issue by Inhibit** [alexrj/Slic3r#3513] opened 2016-09-22 22:27 UTC
### Version

1.2.9, Source 09-22-2016 (3700950474583e6c64163fab848a831cdcfbf44e)
### Operating system type + version

Linux Debian 8 (current as of 09-22-2016), Windows 10 (current patches)
### Behavior

Memory over-run is caused any time the included configs have supports turned on. 

Specific configs used were Simple Mode PETG Support, MakerGeeks Blue PETG, and Simple Mode
Then try to Add... a model to the plate.

I expected the file to finish.

The system gets to Generating support material... on the bottom of the display and then runs the computer out of memory triggering the OOM manager (on Linux, anyway) to start killing off programs. I didn't check memory usage on Windows but from all appearances it does the same.

Test STL and configuration:
[3513-testcase.zip](https://github.com/alexrj/Slic3r/files/491779/3513-testcase.zip)

**Comment by lordofhyphens** [comment] 2017-04-16 00:55
Looks like it works now as of 1857bf63910a7ade053390157fbd1bb9533629a0, using the provided config.ini and STL (which I had been able to reproduce on earlier).
@Inhibit Please verify with a recent Windows build.

![image](https://cloud.githubusercontent.com/assets/31754/25067849/76a36d80-2215-11e7-950e-32d2ab5d3f79.png)


Closing, will reopen if you can reproduce with a *current* build.

**Closed by lordofhyphens** 2017-04-16 00:55 UTC
Labels: Verified bug
