### ISSUE TITLE
[feature request] last resort autocool for external perimeters

### ISSUE THREAD

**Issue by curiouspl2** [alexrj/Slic3r#3079] opened 2015-10-03 04:34 UTC
autocool feature is just cool, but as at different speeds of printing slight variations of pressure 
and way plastic is laid down cause external perimeters to appear slightly different. 
This gives impression of 'uncalibrated' or 'random z wobble' print visually. 

One of solutions to the problem would be option to exclude external perimeters from autocool except completely nessesary (last resort) . This would require autocool to be performed in two phases, 
first excluding external perimeters completely, and then - if layer print time is still below threshold - performing autocool only on external perimeters remaining. 

 greetings, and i wish ultra fine prints :)

**Comment by alexrj** [comment] 2017-03-02 16:09
Duplicate of #2796

**Closed by alexrj** 2017-03-02 16:09 UTC
