### ISSUE TITLE
1.2.7-dev: [print_preset] no longer available

### ISSUE THREAD

**Issue by lordofhyphens** [alexrj/Slic3r#2684] opened 2015-02-22 19:31 UTC
After the commits today, [print_preset] is no longer returning the value of the current preset (it had as of a couple days ago). This has the additional effect of crashing "Send to Printer" as Slic3r tries to upload gcode with [print_preset] and it actually saved it to /tmp/.... with [print_preset] filled out.

**Comment by alexrj** [comment] 2015-02-23 22:42
Uh? It works for me…
How to reproduce?

**Comment by alexrj** [comment] 2015-03-06 09:43
@lordofhyphens, any news? :)

**Comment by lordofhyphens** [comment] 2015-03-09 14:45
The problem seems to be that it is not updating the variable. If I open a
new instance of slic3r the variable isn't available. If I export gcode and
then switch profiles, the name used is the previously active profile.

**Comment by nicksears** [comment] 2015-03-11 19:50
I had an issue where all of my preset placeholders just showed up as their text "print_preset", etc.
Deleting  slic3r.ini (renaming to *.bak) made slic3r start like it was the first time, but fixed the issue.
Had to do a first startup and select expert mode, but worked fine (doesn't delete your presets, but backup just in case)

**Comment by alexrj** [comment] 2015-06-02 19:46
@lordofhyphens, I tested with 1.2.8-dev now and it looks fixed.
Can you confirm? Thank you

**Comment by alexrj** [comment] 2015-06-21 09:19
@lordofhyphens I'm not able to reproduce this with 1.2.9 as well. I tried setting the Output Filename Format to `[input_filename_base]_[print_preset].stl`, then I loaded a file into the plater and then I clicked on *Export G-code...*. The save dialog has the full expanded name with the correct print preset name. Can you help checking please?

**Comment by lordofhyphens** [comment] 2015-06-21 18:44
I will look into reproduction; take a video or something. It doesn't seem
to have a real effect on the output.

**Comment by alexrj** [comment] 2015-06-21 19:47
Well, unless this can be reproduced I'm closing it...

**Closed by alexrj** 2015-06-21 19:47 UTC
Labels: Needs testing with current dev version or next release

**Comment by nicksears** [comment] 2015-06-21 20:43
The issue is that the export dialog loses the actual preset names and just shows the [print_preset], etc.
I have yet to reproduce since I'm using later versions, but it seems to be an issue with the slic3r.ini file in the profiles folder. If anyone ever reproduces it save the slic3r.ini file, I think it may have had something to do with the background processing (which was pretty buggy before 1.2.7). Now it seems great.
