### ISSUE TITLE
Disappearing prompts

### ISSUE THREAD

**Issue by salvatoreone** [alexrj/Slic3r#2933] opened 2015-06-21 14:06 UTC
Why prompts are disappearing so quickly? Fo example the prompt after moving mouse over field of custom G-Code - it is pretty much long and for non native speaker it is not easy to read all text at first attempt. In fact, I am sure it is not possible to read with understanding for native speaker too. Just make them not disappear at all...

**Comment by alexrj** [comment] 2015-06-21 14:33
Duplicate of #2897

**Closed by alexrj** 2015-06-21 14:33 UTC
