### ISSUE TITLE
Bug: Extra layers being generated when support is on.

### ISSUE THREAD

**Issue by nothinman** [alexrj/Slic3r#1475] opened 2013-10-05 17:12 UTC
Hi Alex.

Hit a strange problem today; initially thought it was the STL file being problematic, but ran fix script in netfabb... but this wasn't it.

I'm printing http://www.thingiverse.com/download:53223 from http://www.thingiverse.com/thing:16172/#files (clamp holder, printed flat on bed).

Sliced it with support on, and layers 12 and 14 are some garbage -- Z is not being raised, but it's shown as another layer.

I have then disabled support... but still some support is being generated!

Files: https://www.dropbox.com/sh/22zlck7asj64la3/lOSS1XvHXB

I'm using 0.9.10b on Win 8.

**Comment by lordofhyphens** [comment] 2016-06-03 01:37
Unfortunately the config is a dead link now. I cant reproduce on 1.3.0-dev/Linux with my 0.2 layer height config.

My configuration:
[config.zip](https://github.com/alexrj/Slic3r/files/296801/config.zip)

 It's probably fixed.

![without-support](https://cloud.githubusercontent.com/assets/31754/15766199/914228ce-2901-11e6-9411-9b43f73b70ec.png)
![with-support](https://cloud.githubusercontent.com/assets/31754/15766200/914437f4-2901-11e6-907e-6471403d704c.png)

Going to close this, reopen with more information if you still have problems.

**Closed by lordofhyphens** 2016-06-03 01:37 UTC
Labels: Needs more info
