### ISSUE TITLE
extreme overextrusion in top/bottom layers

### ISSUE THREAD

**Issue by ErikHorn** [alexrj/Slic3r#3446] opened 2016-07-31 20:50 UTC
### Version

1.2.9 and 1.2.9-347-g34f853
### Operating system type + version

Windows 10 64-bit
### Behavior

When printing the attached object, I encountered extreme overextrusion starting in layers 2 or 3. 

The slicing settings for this object are what I'd typically use for other objects. The most notable differences from default settings is that I do not use automatic extrusion width.

Here is a picture of a prior test run to show the problem. The print was aborted shortly into layer 3. The first two layers printed ok.

![img_20160731_134438](https://cloud.githubusercontent.com/assets/13192745/17279298/6f7f2988-5725-11e6-9f64-ee2157a7b80b.jpg)

Here are the first 3 layers from the preview tab. I would expect that layers 2 and 3 should be similar to layer 1.

![layer1](https://cloud.githubusercontent.com/assets/13192745/17279219/d6918398-5723-11e6-9c64-14d504cf0c52.png)
![layer2](https://cloud.githubusercontent.com/assets/13192745/17279227/0bcafe54-5724-11e6-90c0-bb344f98d121.PNG)
![layer3](https://cloud.githubusercontent.com/assets/13192745/17279229/1212a10e-5724-11e6-9dd0-1f9a60640b2e.PNG)

This file contains the STL file, gcode output from slic3r, and the slic3r config file.
[stl_gcode_config.zip](https://github.com/alexrj/Slic3r/files/392629/stl_gcode_config.zip)

**Comment by makertum** [comment] 2016-08-17 11:16
I can confirm this, same issue on OSX 10.11.6, Slic3r 1.2.9. The issue (mysteriously) happens on some STL files, while others are unaffected. Eric's STL file results in the same behavior on my setup, mostly independent of the used settings. The issue seems to be linked to very narrow infill regions (like the narrow region where the dovetail triangles are attached to the object) and can be mitigated by reducing the number of perimeters (effectively leaving more space for the infill).

**Comment by alexrj** [comment] 2017-03-17 18:33
This is fixed as of 1.3.0-dev. Thank you for reporting!

![schermata 2017-03-17 alle 19 33 09](https://cloud.githubusercontent.com/assets/594957/24057715/9c7fdfa4-0b48-11e7-902c-b963217adb0e.png)

**Closed by alexrj** 2017-03-17 18:33 UTC
