### ISSUE TITLE
The bumpy circles don't exist in version 1.2.0 but they do in version 1.2.4-dev

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2502] opened 2015-01-06 12:06 UTC
I loaded the same file into the newest version of Slic3r and an older version (1.2.0). In the older version all the circles were perfect. Can you put the code back the way it was? The gray shape outline is useful though.

![screen shot 01-06-15 at 04 51 pm 2](https://cloud.githubusercontent.com/assets/9621044/5628289/5814193e-95e8-11e4-85e1-b5330e7b5414.jpg)

http://a4jp.com/3d-files/bugs/2015-01-06th-github-test-clip0001.stl
http://a4jp.com/3d-files/bugs/2015-01-06th-09-05-pm-for-github-config.ini

**Comment by alexrj** [comment] 2015-01-06 12:25
I'd rather fix problems.
Anyway, this a duplicate of #2416...

**Closed by alexrj** 2015-01-06 12:25 UTC

**Comment by a4jp-com** [comment] 2015-01-06 12:46
Okay. Sorry I thought my point here was different. I will type in the other thread.
