### ISSUE TITLE
Complete individual Object temperature problem

### ISSUE THREAD

**Issue by IvanBortolin** [alexrj/Slic3r#3200] opened 2016-01-08 22:42 UTC
Hi Ale, 
I think there is a bug in temperature control in mode "complete single object". If in your filament settings you have two different temperature for first layer and another layer, when finish first object and start second object, the printer set first layer temperature, but at second layer don't reset correct temperature.

**Comment by a4jp-com** [comment] 2016-01-09 01:16
That sounds bad. I hope 1.3.0-dev doesn't have this problem. What version are you using?

**Comment by IvanBortolin** [comment] 2016-01-09 09:56
Hi, sorry Ale. By mistake I used version 1.2.6 dev. Now I try whith 1.2.9 and it works well! Thank.

**Comment by a4jp-com** [comment] 2016-01-09 13:01
Nice. Problem solved ^^

**Comment by a4jp-com** [comment] 2016-01-10 12:17
Can you close this thread if the problem is solved?

**Comment by IvanBortolin** [comment] 2016-01-13 22:26
Thank Ale!

**Closed** 2016-01-13 22:26 UTC
