### ISSUE TITLE
Rotated objects slice bad, strange support and weird self intersecting traces

### ISSUE THREAD

**Issue by makertum** [alexrj/Slic3r#2233] opened 2014-08-19 19:32 UTC
Bug found on OSX 10.9.4 with Slic3r 1.7 stable

Slicing the Wades extruder from the Prusa i3 Einstein Rework repository, I noticed Slic3r has a weird bug when I want to slice the BODY-EXTRUDEUR-WADE.stl rotated by 90 degrees clockwise with the Slic3rs built in rotation function in the "Plater" tab.

With no rotation, the GCODE looks ok:
![bildschirmfoto 2014-08-19 um 21 17 55](https://cloud.githubusercontent.com/assets/5277180/3971756/c9a90698-27d6-11e4-9997-f5d20cd5db4f.png)

But just rotating the model 90 degree clockwise yields a unprintable result:
![bildschirmfoto 2014-08-19 um 21 18 20](https://cloud.githubusercontent.com/assets/5277180/3971770/e9ddf5c2-27d6-11e4-97d5-ad776ed0ef0b.png)

Something noticeable weird has happened to the support material, and layer 54 contains some weird self intersecting traces:
![bildschirmfoto 2014-08-19 um 21 23 51](https://cloud.githubusercontent.com/assets/5277180/3971790/098707ce-27d7-11e4-93db-ed82e1347778.png)

BTW, it prints exactly as terrible as it looks here in the GCODE :)

Settings, STL and GCode right here: https://dl.dropboxusercontent.com/u/13860526/Slic3r%20issue%20%232233.zip

Hope that helps making Slic3r even better!

**Comment by lordofhyphens** [comment] 2016-07-18 03:50
Can't reproduce with 1.3.0-dev. Closing. 
![layer_54](https://cloud.githubusercontent.com/assets/31754/16905772/da337a0a-4c70-11e6-9c66-a478ea891e49.png)

**Closed by lordofhyphens** 2016-07-18 03:50 UTC
Labels: Fixed in master branch
