### ISSUE TITLE
About on 1.2.7

### ISSUE THREAD

**Issue by elidorz** [alexrj/Slic3r#2880] opened 2015-06-03 08:43 UTC
Hello alex

windows 7 
slicer 1.2.7
when clicking on about and winsows apper the app freezing , only windows task manager can close the app

elidor

**Comment by kefir-** [comment] 2015-06-03 08:46
This is a known issue, fixed in dev.

**Comment by alexrj** [comment] 2015-06-03 09:07
Thanks, duplicate of #2851 #1788 #2688

**Closed by alexrj** 2015-06-03 09:07 UTC
