### ISSUE TITLE
Feature Enhancement: Separate Top/Bottom Infill Selection

### ISSUE THREAD

**Issue by TheBogueRat** [alexrj/Slic3r#2428] opened 2014-12-18 15:12 UTC
I use hilbertcurve to get a rough finish on the top layer but it takes a long time and shakes my machine enough as it is.  I only need this type of infill on the top so a separate infill pattern selection for each top and bottom would improve my print times and reduce wear on my printer.

Thanks in advance for any consideration!!

**Comment by alexrj** [comment] 2015-01-30 20:57
Thanks, this is a duplicate of #945

**Closed by alexrj** 2015-01-30 20:57 UTC
