### ISSUE TITLE
Alternating direction for perimeters.

### ISSUE THREAD

**Issue by Android78** [alexrj/Slic3r#2733] opened 2015-03-12 00:35 UTC
There doesn't appear to be any option to alternate the direction for perimeters.  
This would be especially useful when trying to print very low layer height.  Tricky areas with low layer height (sloped slide with sharp corners especially), there is a tendency for the head to drag the previous layer which can cause tears in the side of the model if using low or no infill.  By alternating the direction (every even layer clock-wise and odd anticlockwise for example), the plastic that had been dragged on the previous layer would be dragged back on the next.

**Comment by rsatue** [comment] 2015-03-12 13:45
We have noticed the same issue. 

When printing close to the minimum overhang angle, it is always the same corner that tends to curl and it seems to be due to the perimeter printing direction. 

Alternating the direction of the perimeter print would probably compensate the effect of the direction and improve the finishing.

**Comment by alexrj** [comment] 2015-03-12 14:05
Thank you, duplicate of #1073

**Closed by alexrj** 2015-03-12 14:05 UTC
