### ISSUE TITLE
frequent crashes on 1.2.6 precompiled beta on win8x64

### ISSUE THREAD

**Issue by nicksears** [alexrj/Slic3r#2676] opened 2015-02-21 04:53 UTC
I've been using 1.2.6 on windows 8 x 64 for a while and noticed frequent crashes without explanation or dialogue. Usually mid editing part of a profile. Anyone else notice this.

**Comment by cglusky** [comment] 2015-02-23 17:10
Yes.  Both on OS X (latest) and Win7x64.  Had it crash this morning loading a small STL and then again editing a profile.  No errors or dialogues here as well.  Just closes.

**Comment by nicksears** [comment] 2015-02-23 17:35
I'm turning off incremental slicing to see if the actual slicing is causing
the close

On Mon, Feb 23, 2015 at 11:10 AM, Coby <notifications@github.com> wrote:

> Yes. Both on OS X (latest) and Win7x64. Had it crash this morning loading
> a small STL and then again editing a profile. No errors or dialogues here
> as well. Just closes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/2676#issuecomment-75585722>.
>



-- 
Nick Sears, M.S.
Graduate Research Assistant
Biomedical Engineering
Texas A&M University '10
832-289-5518

**Comment by cglusky** [comment] 2015-02-23 17:55
good call.  so far turning off background processing in preferences has fixed it.  i'll update this as i play with it more.  but so far so good.  

makes me want a button in the UI to trigger a Preview and Layer update without needing to Export.

**Comment by nicksears** [comment] 2015-02-23 18:31
I've found it works as well so far, but I loved the new preview of layers
feature and it won't work without  the background processing.

**Comment by alexrj** [comment] 2015-02-23 22:52
Can you provide details and steps for reproducing this? I can't fix it if I can't reproduce it.

**Comment by nicksears** [comment] 2015-02-24 00:54
Windows 8.1x64 Slic3r 1.2.6x64 (1.2.6x32 seems to be ok?)
I've had it happen most commonly when messing with the custom gcode or
rotating/moving parts on the plater
Will post when I have a definite reproducible example

On Mon, Feb 23, 2015 at 4:52 PM, Alessandro Ranellucci <
notifications@github.com> wrote:

> Can you provide details and steps for reproducing this? I can't fix it if
> I can't reproduce it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/2676#issuecomment-75655495>.
>



-- 
Nick Sears, M.S.
Graduate Research Assistant
Biomedical Engineering
Texas A&M University '10
832-289-5518

**Comment by nicksears** [comment] 2015-02-24 00:56
also, this happens whether or not I have any kind of graphics on screen (sometimes in the ptiner tab, sometimes in the plater changing profiles. Probably not a gfx issue then, right? The two systems I primarily use both have synchronized profiles, but one has nvidia, one has ati

**Comment by nicksears** [comment] 2015-02-24 01:04
dropbox link to folder with files I was using when I had it crash:
https://www.dropbox.com/sh/k93l0jwty4sml6s/AAAIDQuVouE7xk3j8-IkSz9fa?dl=0
just plate the stl's and load these profiles and move things around/change parameters.
again, I (think) I've only had it happen on x64

**Comment by justmyopinion** [comment] 2015-02-24 11:12
I see the same random crash now and then. It looks like some thread synchronization as an earlier incident repaired?. I can make it happen randomly just using rotate buttons during background updating. For some reason it does not happen with default settings (not yet).
W7/X64-1.2.6
![crash_exception](https://cloud.githubusercontent.com/assets/5621573/6348127/98725648-bc1d-11e4-8210-cdb8245f57ee.JPG)

**Comment by cglusky** [comment] 2015-02-25 16:42
just had my first crash after turning off background processing.  i was saving to gcode.  sorry, otherwise it's random.  much more stable with background processing turned off.  i was getting crashes during every use.  this is the first crash after processing several print jobs.

win7x64 SP1
intel i7
16GB RAM
AMD FirePro 5900
1TB HD

**Comment by nicksears** [comment] 2015-02-25 16:46
Anyone have an issue with x32 windows or the x32 on x64 windows?

On Wed, Feb 25, 2015 at 10:42 AM, Coby <notifications@github.com> wrote:

> just had my first crash after turning off background processing. i was
> saving to gcode. sorry, otherwise it's random. much more stable with
> background processing turned off. i was getting crashes during every use.
> this is the first crash after processing several print jobs.
>
> win7x64 SP1
> intel i7
> 16GB RAM
> AMD FirePro 5900
> 1TB HD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexrj/Slic3r/issues/2676#issuecomment-75995813>.
>



-- 
Nick Sears, M.S.
Graduate Research Assistant
Biomedical Engineering
Texas A&M University '10
832-289-5518

**Comment by nicksears** [comment] 2015-02-25 19:49
Can confirm multiple crashes on 1.2.6 x32 and x64 using win8.1x64

**Comment by Praesmeodymium** [comment] 2015-03-21 23:11
Loading this thing into slic3r 1.26 crashes me with BG processing on
http://www.thingiverse.com/thing:455865

It also crashes when slicing somewhere around infilling layers
 my system
Operating System: Windows 7 Ultimate 64-bit
           Language: English (Regional Setting: English)
System Manufacturer: MSI
       System Model: MS-7721
               BIOS: BIOS Date: 10/23/12 14:57:22 Ver: 04.06.05
          Processor: AMD A4-5300 APU with Radeon(tm) HD Graphics     (2 CPUs), ~3.4GHz
             Memory: 8192MB RAM
Available OS Memory: 7644MB RAM
       DirectX Version: DirectX 11

**Comment by nicksears** [comment] 2015-03-23 02:44
that slices fine for me with 1.2.6 and 1.2.7 (x64) using my profiles  (https://www.dropbox.com/sh/f2zanfwk0ivwpsc/AAArdV2-hiugT9I7nxaEPBpna?dl=0)

**Comment by ML3D** [comment] 2015-04-29 20:30
I've also experienced crashes with the 64bit 1.2.6 Beta on Win 8.1. Slic3r just vanishes.
Happened a couple of times last night when I was adjusting layer height settings.

**Comment by alexrj** [comment] 2015-06-02 19:47
Okay, all these seem fixed in 1.2.7.  Feel free to reopen if not. Thank you!

**Closed by alexrj** 2015-06-02 19:47 UTC
Labels: Needs more info, Needs test STL file, OS: Windows
