### ISSUE TITLE
1.2.4 current - no brim inside object

### ISSUE THREAD

**Issue by koghe** [alexrj/Slic3r#2488] opened 2015-01-02 17:01 UTC
Brim is not generated with object and large empty regions inside

![screenshot from 2015-01-02 17 58 09](https://cloud.githubusercontent.com/assets/745801/5597798/43ff9a32-92a9-11e4-80e8-e53f5ffa4314.png)

**Comment by MorganSandercock** [comment] 2015-01-04 02:57
Why not just turn on "raft" for 1 layer? Or modify the original model to include brim where you think it is necessary.

**Comment by koghe** [comment] 2015-01-04 10:18
Hi raft double the print time and is not the right way IMHO to solve the problem.
I can design my own brim, but it take time if you have more objects and/or a complex internal geometry, become a real time consuming.
Maybe is not so simple (in term of code and math) apply the same algorithm for the empyt region inside the object. Not a complete brim but a sort of "sewing stitches" on the perimeter can be enough to avoid the adesion problem.

**Comment by alexrj** [comment] 2015-01-04 14:35
It is intentionally not generated for internal holes. It would be very difficult to remove.

**Comment by alexrj** [comment] 2015-01-04 14:36
Anyway, this is a duplicate of #2026

**Closed by alexrj** 2015-01-04 14:36 UTC
