### ISSUE TITLE
1.2.6-x64 crashes at startup on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by joysfera** [alexrj/Slic3r#2654] opened 2015-02-11 13:06 UTC
Slic3r-experimental/bin$ gdb ./slic3r 
(gdb) run
Starting program: /home/joy/Desktop/Slic3r-experimental/bin/slic3r 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe97ba700 (LWP 14567)]
[New Thread 0x7fffe8fb9700 (LWP 14568)]
[New Thread 0x7fffdb77d700 (LWP 14569)]
[New Thread 0x7fffdaf7c700 (LWP 14570)]
[New Thread 0x7fffda77b700 (LWP 14571)]
[New Thread 0x7fffd922a700 (LWP 14573)]
[New Thread 0x7fffd8a29700 (LWP 14574)]
[Thread 0x7fffd8a29700 (LWP 14574) exited]
[Thread 0x7fffd922a700 (LWP 14573) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff25f62d7 in wxWindow::DoSetSize(int, int, int, int, int) ()
   from /home/joy/Desktop/Slic3r-experimental/bin/../dll/libwx_gtk2u_core-2.9.so.3
(gdb) 

Any idea, please? Thanks!

**Comment by alexrj** [comment] 2015-02-11 13:10
Duplicate of #2535

**Closed by alexrj** 2015-02-11 13:10 UTC
