### ISSUE TITLE
Perform Background Processing also while the preset editor dialog is open

### ISSUE THREAD

**Issue by jaggzh** [alexrj/Slic3r#3835] opened 2017-04-03 00:44 UTC
Fresh build on April 2, 2017: 1.2.9-901-g90623c4
OS: Debian Stable

Description:
Background Processing is enabled, but changes in the Print Settings window do not update until the Print Settings window is closed.

**Comment by lordofhyphens** [comment] 2017-04-03 03:05
I can reproduce this on my Debian stable system and on 1.3.0-dev-90623c4 build for Windows.

**Comment by alexrj** [comment] 2017-04-03 10:48
This happens by design.

**Comment by lordofhyphens** [comment] 2017-04-03 13:35
I believe he is interested in a workflow by which he could move the dialog
over and fiddle with it and watch the print update in the background
(instead of assigning overrides)

**Comment by jaggzh** [comment] 2017-04-04 19:48
Yeah -- it's more convenient to change options and see the results than to close the window to see them, or to select every desired option in the quick settings.

**Comment by lordofhyphens** [comment] 2017-06-03 21:26
One additional change should be made here; when we're not using tabs we should be able to manipulate most of the base UI.

**Comment by lordofhyphens** [comment] 2017-06-03 21:51
fccdd12fba788537673d0faba42c61af54956415 addresses the last part in dialog. Closing.

**Closed by lordofhyphens** 2017-06-03 21:51 UTC
Labels: Background Processing, Feature request
