### ISSUE TITLE
Infill way too sparse when using "Combine infill every"

### ISSUE THREAD

**Issue by luotinen** [alexrj/Slic3r#1783] opened 2014-02-16 12:14 UTC
Sorry, I originally posted this in the wrong thread:
https://github.com/alexrj/Slic3r/issues/1288

Combine infill every tooltip text:
"This feature allows to combine infill and speed up your print by extruding thicker infill layers while preserving thin perimeters, thus accuracy. (default: 1)"

Combine infill every actual behavior:
"Will produce sparse vertical infill by skipping a set number of layers. This can be used to speed up print times where the missing infill is acceptable."

To test issue: select 0.100 mm layer height, combine infill every 3 => two layers are skipped and every third is printed at 0.100 mm layer height

To fix issue: select 0.100 mm layer height, combine infill every 3, infill density 300 % => three layers of infill are combined into one 300 % infill layer

![wp_20140216_002](https://f.cloud.github.com/assets/6695329/2180198/626d4d9a-9703-11e3-9862-87701070871e.jpg)
Figure 1. Layer height 0.100, Combine infill every 3, Infill 100 %

![wp_20140216_007](https://f.cloud.github.com/assets/6695329/2180199/6c9c2926-9703-11e3-93e7-c2ab97ccb9c2.jpg)
Figure 2. Layer height 0.100, Combine infill every 3, Infill 300 %

Slic3r 1.0.0.RC1 via Repetier-Host V0.95F Windows 7 64x

**Comment by lordofhyphens** [comment] 2015-04-12 18:49
I can indeed confirm that this problem is in 1.2.7. Breaks stuff like 3d honeycomb.

Working on a fix. Currently the only idea I've got is to add a multiplier to the flow amount corresponding to the layer height at line 222 in Fill.pm.

This would need a check, however, to not exceed the nozzle diameter, and basically forces any combination to fit inside the maximum layer height for the nozzle. However, since this internal infill isn't actually seen, I might experiment a bit with deliberately overextruding.

**Comment by lordofhyphens** [comment] 2015-04-12 21:27
Pull request is up for the fix I mentioned earlier. You can use the branch, infill-combine, from my version until then.

**Comment by lordofhyphens** [comment] 2015-04-19 06:00
Hastebin of the diff:
http://hastebin.com/erososelap.pl

**Comment by lordofhyphens** [comment] 2016-06-18 02:24
I've added a link to the tree to the pull request thread.

**Comment by lordofhyphens** [comment] 2016-06-30 04:12
Okay, it's merged in. I added an additional safety; slic3r still won't let you make layers thicker than the nozzle diameter. So if your nozzle diameter is 0.8mm, layer height is 0.1mm and you ask for 10 combined, it'll give you 8 in reality. This is in keeping with not letting you set bigger layers than your nozzle diameter. 

I might be convinced to relax this as a super-experimental setting but frankly I'm not particularly sold on it being even a workable idea.

If we wanted to set a nominal "maximum layer height" in the Printer settings or something we could probably get Slic3r to autocalculate infill combination w/o much trouble at all.

**Comment by alexrj** [comment] 2016-07-10 10:24
No, wait, that check is already done in the main logic of infill combination (see `combine_infill()` in Slic3r::Print::Object); it should not be duplicated in Fill.pm.

Regarding the main issue, I think the patch is not a proper change and I'd like to do more investigation for understanding the issue better. Since this issue was created (Feb 2014) a lot of changes were applied to the flow calculation:
https://github.com/alexrj/Slic3r/commits/master/lib/Slic3r/Fill.pm

I hope you don't mind if I temporarily revert those commits, and we proceed with actual tests and numbers, and writing a regression test before applying any patch.

I just did one test with 2811af349ae17230a525ddcf819b1ddffaa250c9 (i.e. before the three patches) to compare these two situations:

```
layer_height = 0.2
infill_every_layers = 2
```

and

```
layer_height = 0.4
infill_every_layers = 1
```

I expect internal infill to be identical in both cases. And in fact, Slic3r is using the same flow rate (mm3_per_mm) in both cases. So I can't replicate the issue as of that commit. Can you help me to study the issue with real numbers?

**Comment by lordofhyphens** [comment] 2016-07-10 15:07
Still your repo, I have just been trying to fix what I thought I could.

**Comment by lordofhyphens** [comment] 2016-07-10 16:47
From my own experimental testing (and looking at the preview), Slic3r was introducing gaps between the successive layers of infill. This was most noticeable with 3D honeycomb and combined infill and lines up with what @luotinen experienced.

Test case: [test_case.zip](https://github.com/alexrj/Slic3r/files/356098/test_case.zip)
This is with 1d510f76dbec34fdda0db2e3fb8635dc3475a728.

Test print indicates that the gcode output is *exactly* what the preview says it should be. 

Example screenshots:
![combined](https://cloud.githubusercontent.com/assets/31754/16714646/7ad79280-468f-11e6-9d20-d46b8c7a5e48.png)
![cube-3d-honey1](https://cloud.githubusercontent.com/assets/31754/16714651/8b6c98a2-468f-11e6-9a09-5d5c636e0d09.png)
![cube-combine_rect](https://cloud.githubusercontent.com/assets/31754/16714653/8b6e8432-468f-11e6-92c4-f963b1f388d0.png)
![cube-honeycomb](https://cloud.githubusercontent.com/assets/31754/16714652/8b6ccee4-468f-11e6-8eb5-0bbb602e438c.png)

P
![print_test](https://cloud.githubusercontent.com/assets/31754/16714761/fcb91a14-4692-11e6-9fa8-5de2063967ab.jpg)

**Comment by lordofhyphens** [comment] 2016-07-10 17:01
A diff of the same cube, with 3x combined vs 1x combined (same pattern, same model) indicates that slic3r is indeed generating exactly the same amount of flow for infill.

I'll play around with this and see if I can devise a good test, but here's the gcode from two slices of the same object. I used relative E distances and did a diff of the two. The only infill that differs here is that the combined infill is missing lines that are in the original.

[comparison.zip](https://github.com/alexrj/Slic3r/files/356113/comparison.zip)

So whatever is happening w/r/t flow rate, it's either being reset or something; I don't know.

**Comment by lordofhyphens** [comment] 2016-07-10 23:06
combine_infill() is getting called and it's adding new surfaces with the appropriate layer height.

**Comment by lordofhyphens** [comment] 2016-07-10 23:27
I put a snoop in to check the mm^3 and layer height for all infill path roles. It looks like the mm3_per_mm is getting clobbered somewhere.

mm3: 0.218711 0.35
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.3
mm3: 0.125664 0.1

**Comment by lordofhyphens** [comment] 2016-07-11 00:33
Results after patch: 
mm3: 0.439823 0.35
mm3: 0.376991 0.3
mm3: 0.125664 0.1

**Closed** 2016-11-22 17:36 UTC
Labels: Fixed with PR available to merge, Gap Fill or Infill
