### ISSUE TITLE
horizontal contact distance for supports ?

### ISSUE THREAD

**Issue by jfpion** [alexrj/Slic3r#3298] opened 2016-04-06 06:01 UTC
slic3r 1.2.9
win 7 64

the pb with support with some plastic is th supports stick to well to the part horizontally. there is a distance  Z contact tunable but not a horizontally distance contact avaible to tune

it could be a new feature

specially useful for the small intricate supports
thank you

**Comment by lordofhyphens** [comment] 2016-04-06 14:06
Duplicate of #2916

**Closed by lordofhyphens** 2016-04-06 14:06 UTC
Labels: Duplicated Issue
