### ISSUE TITLE
Custom top solid infill extrusion width causes infill to not reach perimeters

### ISSUE THREAD

**Issue by nathanielhudson** [alexrj/Slic3r#2697] opened 2015-02-28 23:58 UTC
Slic3r version: 1.2.6 experimental

Operating system: OSX 10.10.1

Steps to reproduce the issue:
- Set top solid infill extrusion width to a small number (0.1, for example)
- Set infill extrusion width to automatic (0)
- Slice a model with a flat upper surface
- (Optional) Print

Expected result:

Infill will reach perimeter

Actual result:

The top solid infill area appears to be calculated using the standard infill extrusion width width, and does not reach perimeter. This is visible in the preview pane and on the actual print.

![screenshot](https://cloud.githubusercontent.com/assets/2744848/6428779/aacc270e-bf7b-11e4-91ce-fbf09f4292c4.png)

![photo](https://cloud.githubusercontent.com/assets/2744848/6428784/b9b16ff4-bf7b-11e4-9639-c4c8f54daf2a.PNG)

G-code:

https://gist.github.com/hhhudson/ed7ad080f56415a68f55

Config.ini:

https://gist.github.com/hhhudson/d25025ba57d20e7a426e

STL, OBJ or AMF input file:

http://www.thingiverse.com/thing:39050

**Comment by alexrj** [comment] 2015-03-06 09:43
Thank you for the very detailed report, I appreciate it.

**Comment by alexrj** [comment] 2015-03-06 10:02
This can also be reproduced with default settings and a low Top Solid Infill Extrusion Width (like 0.1mm).
Note to self: this is caused by the `$distance_between_surfaces` logic in Fill.pm

I'll fix this in 1.3.x as it requires some important changes to the code.

**Comment by lordofhyphens** [comment] 2017-03-06 02:19
How's this relate to the move to c++ infill?

**Comment by alexrj** [comment] 2017-03-11 23:58
I'm not able to reproduce this on master anymore, but I tested again on 1.2.6 and I can reproduce with that one. The issue is fixed but I need to write a regression test before closing this.

**Comment by alexrj** [comment] 2017-03-12 10:39
Regression test added. We can safely close this issue. Thank you for reporting it.

**Closed by alexrj** 2017-03-12 10:39 UTC
