### ISSUE TITLE
Solid infill of bottom layer is missing

### ISSUE THREAD

**Issue by metalzse** [alexrj/Slic3r#3503] opened 2016-09-13 12:54 UTC
### Version

Slic3r Version 1.2.9
### Operating system type + version

Windows 10 Pro, Version 1511
### Behavior
- _Describe the problem_ 
  Solid infill of bottom layer is missing.
  I configured 3 bottom layers in settings, but only 2 of them are actually produced in gcode.
- _Steps needed to reproduce the problem_ 
  Normal slicing with provided config.ini
- _Expected Results_ 
  I expect that 3 solid build layers are printed after the support interface layer.
- _Actual Results_ 
  The first of 3 solid layers is not produced in gcode resulting in only 2 solid bottom layers.
  - _Screenshots from ___Slic3r___ preview are preferred_ 

Layer Z = 21.20:
Dark-grey is the last support interface layer; whereas blue and red are model layers.
![z21p20](https://cloud.githubusercontent.com/assets/7773679/18473618/35ea513c-79be-11e6-84ad-809fefb77175.png)

Layer Z = 21.25
Dark-grey is the support structure, where light-grey is the preview of the next layer.
![z21p25](https://cloud.githubusercontent.com/assets/7773679/18473621/3affca4e-79be-11e6-93b4-3fe47ff0a5e2.png)

Layer Z = 21.45
The problem appears in this layer. As you can see, in the light-grey area, the solid infill surface is completely missing – i.e. the first bottom layer.
![z21p45](https://cloud.githubusercontent.com/assets/7773679/18473624/3fbeb61c-79be-11e6-88c4-941d2dd640b6.png)

Layer Z = 21.55 
Dark-grey is the support structure, where light-grey is the preview of the next layer.
![z21p55](https://cloud.githubusercontent.com/assets/7773679/18473625/43d7e5a2-79be-11e6-9d83-46cf446dee52.png)

Layer Z = 21.7
In this layer, the next solid infill is produced – no problems observed. However, because the underlying solid layer was not printed before (see Z = 21.45), this layer exhibits crappy surface quality.
![p21p70](https://cloud.githubusercontent.com/assets/7773679/18474210/56f8fa38-79c1-11e6-9242-fc5b20a9ff86.png)

The following layers are printed without problems.
#### STL/Config (.ZIP) where problem occurs

[Slic3r Bug Report.zip](https://github.com/alexrj/Slic3r/files/469805/Slic3r.Bug.Report.zip)

**Comment by bubnikv** [comment] 2016-11-28 08:09
This seems to be working fine in Slic3r 1.31.6 Prusa Edition.

The problem in the alexrj slic3r may be caused by the way the Clipper library offset is applied over multiple polygons at once, which is deemed unsafe. The offset shall be applied per contour, then the contour shall be merged.

**Comment by alexrj** [comment] 2016-12-17 10:26
Thank you @metalzse, I fixed this.
It was caused by support_material_contact_distance == 0 and other rare circumstances related to bridge detection.

**Closed by alexrj** 2016-12-17 10:26 UTC
