### ISSUE TITLE
Preview shows infill overlapping perimeters on one layer - caused print fail?

### ISSUE THREAD

**Issue by mattster98** [alexrj/Slic3r#3215] opened 2016-01-21 13:24 UTC
Started happening with one particular model.  Printed it once just fine, even though I noticed the weirdness in the preview.  Next time I re-sliced it to try and make it go away, but it was still there, just different.  Caused the print to shift on one axis at the layer with the weirdness.  Confirmed the thickness of the pre-fail resulting print is 5.6mm - same as the layer where the preview shows strange infill.

I checked the STL in netfabb and it didn't find any problems.

Here's how it looks on the preview:
![gigantic_infill](https://cloud.githubusercontent.com/assets/1469426/12481367/a295a136-c016-11e5-8383-14e06725a2e5.jpg)

And the resulting prints (the one in white I noticed and killed, then pulled off most of the messed up part):
![img_20160121_081238](https://cloud.githubusercontent.com/assets/1469426/12481415/fd88fd54-c016-11e5-9c19-24ec90946555.jpg)
![img_20160121_081252](https://cloud.githubusercontent.com/assets/1469426/12481416/003c904c-c017-11e5-98af-b1c665cd5446.jpg)

Settings file - refer to ones with "weird_infill" suffix...  I had been tweaking trying to make this go away.
[weird_infill_settings.ini.txt](https://github.com/alexrj/Slic3r/files/99159/weird_infill_settings.ini.txt)

STL File:  http://www.thingiverse.com/thing:872507

Resulting gcode: 
[Cutter_Tool_Holder-weird-infill.zip](https://github.com/alexrj/Slic3r/files/99162/Cutter_Tool_Holder-weird-infill.zip)

**Comment by lordofhyphens** [comment] 2016-01-21 22:54
Try setting Gap Fill Speed = 0 and check the output, or setting your infill width to some fixed value. 

I've been wondering where this could live myself.

**Comment by lordofhyphens** [comment] 2016-01-21 22:58
I wonder if this is related to #3172

**Comment by mattster98** [comment] 2016-01-22 02:15
Changing Gap Fill Speed to 0 didn't change anything (that I could tell from the preview).  Infill extrusion width was 0.45.  Tried changing that to 0 and I think that made it worse.

![even_more_gigantic_infill](https://cloud.githubusercontent.com/assets/1469426/12500740/c5759518-c083-11e5-95a0-204de29e5040.jpg)

Tried changing the default extrusion width to 0 (along with infill width) and it seems to have helped.  Still some sort of visible artifact at 5.6mm height.

![better_but_still_weird](https://cloud.githubusercontent.com/assets/1469426/12500770/123c9f22-c084-11e5-81b4-a64de8ce5435.jpg)

**Comment by mattster98** [comment] 2016-03-25 01:14
I may have run into another instance of this.  Doesn't have the same visual indication on the preview, but several attempts at printing this one model with changes to settings each time (and even changes to the model)  have yielded a failure similar to the above at a relatively similar Z height.  Makes the printer appear to have skipped steps, but other models print fine..

Is there a way to more easily hunt through the gcode to try and find the line(s) that may be the cause?  I'd love to be able to confirm if this is the explanation.

**Comment by lordofhyphens** [comment] 2016-03-25 15:45
Not really, finding overlaps like that is hard to do without being able to
visualize the 3d space.

**Comment by mattster98** [comment] 2016-03-25 16:06
Is there a visualizer that shows the gcode more sequentially rather than
based on Z-height?  gcode.ws, slic3r's built-in, and octoprint's built-in
are all I've used.

**Comment by lordofhyphens** [comment] 2016-03-25 20:37
Yagv perhaps.

**Comment by alexrj** [comment] 2016-03-26 18:56
This looks fixed as of current stable branch (1.2.10-dev):

![schermata 2016-03-26 a 19 54 33](https://cloud.githubusercontent.com/assets/594957/14061882/a99b1214-f38c-11e5-8829-ec8faee95c6a.png)

I need to test more with 1.3.0-dev as it's either hanging or taking too much time. This is a very tricky model.

**Comment by DrLex0** [comment] 2016-11-15 16:59
I have another model that exhibits this problem very prominently. The infill breaks outside the perimeters and is excessively thick. I didn't even try to print this but I am sure it would have ended in disaster.
When this bug occurs, it is always when I either enforce a specific default extrusion width, or a specific perimeters width. If I leave both at 0 (auto), the problem goes away. Setting an external perimeter width does not seem to cause problems.

![extrusionfail1](https://cloud.githubusercontent.com/assets/16401844/20310877/e0cf21ca-ab4d-11e6-8b28-efc69e0ed90f.png)
![extrusionfail2](https://cloud.githubusercontent.com/assets/16401844/20310879/e0d652c4-ab4d-11e6-8e3f-6cf54dc99f29.png)
This looks like a delicious cake! What it should look like:
![extrusionok](https://cloud.githubusercontent.com/assets/16401844/20310878/e0d3d0da-ab4d-11e6-9b97-73f9a2350530.png)

The model and settings:
[ModelAndConfig.zip](https://github.com/alexrj/Slic3r/files/592356/ModelAndConfig.zip)

**Comment by lordofhyphens** [comment] 2016-11-15 18:17
@DrLex0 have  you checked it with current stable branch?

**Comment by DrLex0** [comment] 2016-11-15 23:14
I have checked it with the latest Prusa3D build which does not have it (but as far as I understand from the release notes, they basically locked down some of the automatic infill parameters to circumvent this problem).
I haven't tried it with the official Slic3r branch because building it in OS X 10.11 was a royal pain the last time I tried it.

**Comment by bubnikv** [comment] 2016-11-16 08:20
> I have checked it with the latest Prusa3D build which does not have it (but as far as I understand from the release notes, they basically locked down some of the automatic infill parameters to circumvent this problem).

In the latest Prusa3D code, the automatic line width adjustment is enabled to some extent, limited to +20%.

Also a similar issue you experienced is caused by a bug in the "turn bottom surfaces to internal bridges" feature, which may in some cases produce extrusions outside the object.

**Comment by alexrj** [comment] 2016-12-21 16:15
Thank you @DrLex0, I fixed that.

@bubnikv, this was actually caused by `adjust_solid_spacing()` not being idempotent and increasing spacing by 20% each time it was called during a single `fill_surface()` run.

**Closed by alexrj** 2016-12-21 16:15 UTC
