### ISSUE TITLE
panic: fold_constants JMPENV_PUSH returned 2 

### ISSUE THREAD

**Issue by kino3d** [alexrj/Slic3r#3050] opened 2015-08-23 21:49 UTC
panic: fold_constants JMPENV_PUSH returned 2 at /usr/local/share/perl/5.20.1/Sub/Quote.pm line 3.
current git 
ubuntu 15.04 
 perl -v
This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi

is perl 5.20 supported? 

i don't have a config ini to send :)

![selection_010](https://cloud.githubusercontent.com/assets/745801/9430337/7fb13216-49f1-11e5-802c-83457cb2870a.jpg)

**Comment by alexrj** [comment] 2017-03-20 22:17
I'm closing this one because 1) nobody was able to reproduce it; 2) it's an upstream issue; 3) we now support 5.24 :-)

**Closed by alexrj** 2017-03-20 22:17 UTC
