### ISSUE TITLE
Feature Request: Amount of plastic needed for prints

### ISSUE THREAD

**Issue by gvJaime** [alexrj/Slic3r#1205] opened 2013-06-01 16:38 UTC
My problem was that slic3r doens't tell me how much plastic will it use. And from which extruder.
For example, it would be great that if I have a print in ABS, with PVA supports, slic3r told me how much will it need of each of them.

I'm not sure if there is any program that calculates that from the gcode or something, like pronterface or repetier. Or if slic3r already does it. I was searching when I accidentally posted.

(EDIT: Copied from below --@lordofhyphens)

**Comment by lordofhyphens** [comment] 2017-03-01 20:44
Duplicate of #647 (associated PR at #3669).

**Closed by lordofhyphens** 2017-03-01 20:44 UTC
Labels: Feature request
