### ISSUE TITLE
[Placeholder] and math?

### ISSUE THREAD

**Issue by sebbe90** [alexrj/Slic3r#3743] opened 2017-03-08 17:30 UTC
### Version
1.2.9

### Operating system type + version
Windows 7

### Behavior
At the moment I try to implement for our Hyrel Multi Head printer a custom tool change code. Therefore I need to add explicit "T1" (with values 1 2 3 4) to use extruder 1 for the new tool. If I use [next_extruder] or [current_extruder] the counting begins with zero, so in principal it is possible, but the numbers are one digit to low. Is there a possibility to simply add a one so something like "T[next_extruder]+1".

Regards.

**Comment by lordofhyphens** [comment] 2017-03-08 18:05
Duplicate of #3390 and #2407

**Closed by lordofhyphens** 2017-03-08 18:05 UTC
Labels: Duplicated Issue
