### ISSUE TITLE
Pillar supports in 1.2.0 too thin

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2219] opened 2014-08-14 17:00 UTC
I've been getting some pillars that are really thin and get knocked over mid-build frequently, even when support is printed at 10mm/s.

The screenshot below shows the cross-section of one of the pillars, which appears to be about 1x2mm  wide.
![screenshot13](https://cloud.githubusercontent.com/assets/88355/3923408/4ba8f372-23d3-11e4-93dd-c704ec695dd2.png)

Full G-code is here: https://gist.github.com/f873319fdaf27ff65078

**Comment by lordofhyphens** [comment] 2016-07-05 18:11
Suspect this is a duplicate of #2170. Closing, please continue there.

**Closed by lordofhyphens** 2016-07-05 18:11 UTC
Labels: Duplicated Issue
