### ISSUE TITLE
[BUG] Bottom Infill does not touch perimeters at 0.05mm layers 

### ISSUE THREAD

**Issue by avalero** [alexrj/Slic3r#2682] opened 2015-02-22 11:12 UTC
Infill does not touch perimeters (as in picture)
Slicr v. 1.2.6 (experimental)
STL, gcode and config -> https://drive.google.com/folderview?id=0BwJrSRUCej0UNmJ5Z2JCd3dZbjQ&usp=sharing

![dsci0515](https://cloud.githubusercontent.com/assets/1442682/6318315/d4405c12-ba8b-11e4-88bd-999eb869aefc.JPG)

**Comment by alexrj** [comment] 2015-03-06 10:14
Hi @avalero, good catch.   This is caused by the same issue as #2697.

**Comment by alexrj** [comment] 2017-03-12 10:45
This is fixed as of current master, and covered by a regression test:

![schermata 2017-03-12 alle 11 45 12](https://cloud.githubusercontent.com/assets/594957/23831056/6e9ac622-0719-11e7-8bd5-fd8af6efa18b.png)

**Closed by alexrj** 2017-03-12 10:45 UTC
