### ISSUE TITLE
Feature request: Override brim setting

### ISSUE THREAD

**Issue by hyperair** [alexrj/Slic3r#2964] opened 2015-07-01 03:16 UTC
I usually print without a brim, but for some prints with extremely tiny bases I do need them, and it would be nice if I could specify this without maintaining a different print profile for it. Brim width isn't listed in the list of settings you can override for a print.

**Comment by whosawhatsis** [comment] 2015-07-01 03:40
duplicate of https://github.com/alexrj/Slic3r/issues/1316

**Comment by Lenbok** [comment] 2015-09-11 23:11
Also, duplicate of #2163 and #2164

**Comment by alexrj** [comment] 2015-11-04 19:08
@hyperair, see #2163

**Closed by alexrj** 2015-11-04 19:08 UTC

**Comment by hyperair** [comment] 2015-11-05 03:49
Hmm, I guess I wanted a way to override this per-print, rather than having to mess up my configured print profiles.

**Comment by alexrj** [comment] 2015-11-05 10:12
Just change it under "Print Settings" and don't save the changed profile.
