### ISSUE TITLE
Some interruptions on the external perimeters ver.1.2.0

### ISSUE THREAD

**Issue by 3DPRN** [alexrj/Slic3r#2207] opened 2014-08-08 17:47 UTC
OS:Windows 7 64Bit using Slic3R 32bit ver.1.2.0

![image](https://cloud.githubusercontent.com/assets/8396924/3860429/ebfbb080-1f23-11e4-9a7b-49d391bb35fc.png)

With some STLI've got some interruptions in some layers for the external perimeters.
With old version ex.1.1.6 there was no problem

File  Config:
http://www.3dprn.com/tmp/Config_slic3r.ini.txt
STL File:
http://www.3dprn.com/tmp/TMP_55355406_objs.stl
THX
Gianfranco Fazzini

**Comment by alexrj** [comment] 2015-06-02 20:32
Ciao Gianfranco!

I'm closing this one as this behavior can't be reproduced as of recent versions, and also because it's mainly caused by wrong rendering by Repetier Host. Now we have built-in 3D preview in Slic3r. Physical prints have no gap problems.  Let me know if you have any other problem.

**Closed by alexrj** 2015-06-02 20:32 UTC
