### ISSUE TITLE
Infill every N layers is not using the right infill pattern

### ISSUE THREAD

**Issue by SeanSolberg** [alexrj/Slic3r#3536] opened 2016-10-16 14:43 UTC
### Version

1.2.9
### Operating system type + version

Windows 10
### Behavior

I'm printing a cylinder shaped object that changes widths as it builds up.    I'd like to keep all the movements in a circular pattern as much as possible for speed, reduced vibration, etc.  Slic3r is choosing the rectilinear fill pattern for the infills for all of the "solid infill every n layers.  I have the Fill Pattern set to "concentric" and i have the top/bottom fill pattern set to concentric. 

[Slic3r_cylindar_infill_issue.zip](https://github.com/alexrj/Slic3r/files/531878/Slic3r_cylindar_infill_issue.zip)
![cylindar1](https://cloud.githubusercontent.com/assets/2372894/19418194/e09839ac-9384-11e6-8b6e-396a1454e441.png)
![cylindar2](https://cloud.githubusercontent.com/assets/2372894/19418195/e30318ba-9384-11e6-941a-4e45f18a91f8.png)

_Is this a new feature request?_  Not sure if this is a bug or a new feature request

**Comment by lordofhyphens** [comment] 2016-10-16 14:50
That is intended behavior; "solid" infill is rectilinear.

If you want 100% concentric circles, make a modifier mesh of thin
rectangles and set the infill % for the mesh.

**Comment by mrjohnc** [comment] 2016-11-04 10:23
@lordofhyphens could this also be achieved by specifying a very high number of perimeters?

**Comment by SeanSolberg** [comment] 2016-11-04 13:03
Yes, that's what I did.  It applied it to the whole object, even where I
didn't need that.  However, it helped.

**Comment by lordofhyphens** [comment] 2017-01-25 16:52
This is now done using modifier meshes like I mentioned above. 1.3.0-dev now has modifier meshes  you can define and place in Slic3r itelf.

Closing as it's not actually a bug. You will want to set top/bottom solid layers to 1 as well when doing this.

**Closed by lordofhyphens** 2017-01-25 16:52 UTC
Labels: Modifier Mesh use-case, Not a bug
