### ISSUE TITLE
The pan in the 3D view area jumps a little bit and drops the pan sometimes.

### ISSUE THREAD

**Issue by a4jp-com** [alexrj/Slic3r#2454] opened 2014-12-26 17:05 UTC
Windows 7 64-bit
Slic3r 1.2.2 dev (2014-12-27th 2:04 a.m.)

It is fantastic having the pan turned on for the middle button! Thank you so much.

It almost works perfectly but it jumps a little bit when panning. The right mouse button doesn't seem to have the same problem.

Both pan buttons seem to drop the pan sometimes while panning. I'll make a video and attach it here in a few minutes.

Maybe this isn't the best video but I'll try and upload a better one soon if needed.
![2014-12-27th](https://cloud.githubusercontent.com/assets/9621044/5558718/6311dc98-8d75-11e4-92fd-e9a4fe61fce9.gif)

**Comment by alexrj** [comment] 2015-01-07 10:59
There was a minor issue when panning with the middle button. It's fixed now. I can't reproduce the issue anymore. Can you confirm that we can close this? Thank you

**Comment by a4jp-com** [comment] 2015-01-08 06:03
It still jumps a bit but it is almost perfect ^^

**Closed** 2015-01-18 21:03 UTC
Labels: Fixed, Needs testing with current dev version or next release
