### ISSUE TITLE
draw Preview and Layers with selected Z after Settings change

### ISSUE THREAD

**Issue by efa** [alexrj/Slic3r#3022] opened 2015-07-27 14:38 UTC
Open an STL, lets slice it.
Go to a Plater,Preview tab and select an intermediate Z level
Go to a Plater,Layer tab and select an intermediate Z level
Go to Print Settings, change Infill or Support material settings (or some other)
Back to Plater tab,Preview tab, the right Z slider is set to the previous level, but the Preview show Z=max
Back to Plater tab,Layer tab, the right Z slider is set to the previous level, but the Preview show Z=max
Moving the Z slider a little and back, re-draw (up to) the selected layer.

Please show the current selected layer after a Settings change, this is very usefull to compare the effect of Infill/Support setting change
Slic3r 1.2.9 on Ubuntu

Would be nice to have an option to select Z slider unit settings, to mm or layer number.

**Comment by teppix** [comment] 2015-07-30 12:18
Looks like a duplicate of https://github.com/alexrj/Slic3r/issues/2963 (except for the z-slider unit request)

**Comment by alexrj** [comment] 2017-03-20 22:19
This was done a long time ago. Thanks :)

**Closed by alexrj** 2017-03-20 22:20 UTC

**Comment by efa** [comment] 2017-03-20 22:52
done in the git sources, but not released?
For the RFE: Z slider unit settings (mm or layer number), do you prefer a new issue?

**Comment by lordofhyphens** [comment] 2017-03-20 23:03
@efa get a build from http://dl.slic3r.org/dev

Prefer a new issue for separate things, check to make sure it isn't already in the issue tracker though.

I don't think having the slider in terms of layer # makes any sense at all once  you realize that not everything is necessarily on the same layer (combined infill, any support, etc).

**Comment by efa** [comment] 2017-03-21 10:16
thanks for pointing me to prebuilt dev versions, I will test.

For the RFE, done in #3783

**Comment by lordofhyphens** [comment] 2017-03-23 18:06
Delete the entire dir and check it out again. Do not use sudo to build.

**Comment by efa** [comment] 2017-03-24 17:36
Open an STL, lets slice it.
Go to a Plater,Preview tab and select first/bottom Z layer.
Go to Print Settings, change Infill, Bottom settings
Back to Plater tab,Preview tab, the right Z slider is set to last/upper layer, and Preview show Z=max
Moving the Z slider back to first/bottom Z layer, show the layer with the new settings.

Please keep the Preview selected Z layer for Infill, Bottom settings too.
I can confirm it is solved for Layers tab with 1.3.0 dev
