### ISSUE TITLE
weird gcode outside of model

### ISSUE THREAD

**Issue by kameamea** [alexrj/Slic3r#3616] opened 2016-12-14 21:40 UTC
### Version 
1.2.9
### Operating system type + version
ubuntu 16.04

### Behavior
the top three levels of the gcode are outside of the stl model.
See the attached screenshots. I checked with blender that the stl is a manifold.
I expect the outside of the gears to be in a straight line.

![gear_model](https://cloud.githubusercontent.com/assets/7243765/21195279/6e0b9d56-c233-11e6-9998-bfb0eb8cd1f4.png)
![gear_gcode](https://cloud.githubusercontent.com/assets/7243765/21195280/6e0dabfa-c233-11e6-8aa4-7b17102cb49b.png)

#### STL/Config (.ZIP) where problem occurs
[issue.zip](https://github.com/alexrj/Slic3r/files/653343/issue.zip)

**Comment by lordofhyphens** [comment] 2016-12-14 21:43
Github may be acting case-sensitive. ".zip" should work as an extension (I
don't know if it extracts it or performs any other verifications).

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by kameamea** [comment] 2016-12-14 21:45
I tried .zip and .ZIP  and different content with no success. May I email the zip file to you so you can attach it?

**Comment by lordofhyphens** [comment] 2016-12-14 22:46
Yeah, that's fine. Use the email on my profile.

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Comment by lordofhyphens** [comment] 2016-12-15 00:33
Not seeing it in 1.3.0-dev, so that's something. 

Turn off thin wall detection as a workaround.

![image](https://cloud.githubusercontent.com/assets/31754/21207063/7bc0c76c-c22b-11e6-9261-5dceb5afdee2.png)

![image](https://cloud.githubusercontent.com/assets/31754/21207110/d14f5ac2-c22b-11e6-9320-787e6ca5f6b1.png)

**Comment by lordofhyphens** [comment] 2017-01-25 16:38
No other comments from @kameamea and I couldn't reproduce and it's been over a month. Closing.

**Closed by lordofhyphens** 2017-01-25 16:38 UTC
Labels: Can't Reproduce - Development Build
