### ISSUE TITLE
Slic3r crashes when setting a Circular Bed Shape to 00mm in diameter

### ISSUE THREAD

**Issue by UserWL** [alexrj/Slic3r#3639] opened 2016-12-27 06:49 UTC
### Version
Slic3r v1.2.9 bundled with Repetier-Host v1.6.2

### Operating system type + version
Windows 8.1

### Behavior
Slic3r crashes when setting the Bed Shape to Circular with a Diameter of "00" mm. Also, crashes for diameters of "000", "0000", and so forth. See screenshots for steps to replicate bug.

![step 1](https://cloud.githubusercontent.com/assets/7088681/21492911/30006d6e-cbbd-11e6-8af2-cc5aa89ef671.PNG)
![step 2](https://cloud.githubusercontent.com/assets/7088681/21492912/301e1774-cbbd-11e6-8935-6570a0441037.PNG)
![step 3](https://cloud.githubusercontent.com/assets/7088681/21492913/30273e12-cbbd-11e6-8ff5-8a831af77432.PNG)
![step 4](https://cloud.githubusercontent.com/assets/7088681/21492914/30287bce-cbbd-11e6-955d-403801be1b27.PNG)
![step 5](https://cloud.githubusercontent.com/assets/7088681/21492915/302c7cc4-cbbd-11e6-94f5-7c609567515b.PNG)

**Comment by lordofhyphens** [comment] 2017-01-25 16:22
Duplicate of #3681

And it's been fixed in a PR.

**Closed by lordofhyphens** 2017-01-25 16:22 UTC
Labels: Duplicated Issue, Fixed with PR available to merge
