### ISSUE TITLE
RC2 Support material too close to object.

### ISSUE THREAD

**Issue by MidnightSmoker** [alexrj/Slic3r#1686] opened 2014-01-09 01:19 UTC
Hello, 
I am having an issue with RC2..
The Support Material is too close to the object walls, so much so that they fuse together and it is impossible to remove the support material. 
Here is a screen shot of the support material in question:
![closesupport](https://f.cloud.github.com/assets/4566356/1874238/8a018a5c-78cb-11e3-8c34-ceeb03bdde67.png)

Both the raft and the walls around the support are too close and fuse to the object. If I could tell Slic3r to move the support X mm away from the object walls that would solve my problem.

I have tried every setting in the support config and haven't been able to resolve this issue. If there is anything I have missed, or some tweak I can do manually to the config files I would appreciate the info.

Thanks

**Comment by lordofhyphens** [comment] 2016-06-27 22:26
Duplicate of  #1539

**Closed by lordofhyphens** 2016-06-27 22:26 UTC
